LuckyPennySoftware/AutoMapper

- src/AutoMapper/QueryableExtensions/Extensions.cs
I hit this exception and was wished it would actually tell me which property couldn't be mapped. This change helped me and maybe it could help someone else.
The exception goes from reading like this 
```
Unable to create a map expression from System.Nullable`1[System.Int32] to System.Int32
``` 
to reading like this 
```
Unable to create a map expression from InvoiceItem.ProductId (System.Nullable`1[System.Int32]) to InvoiceItemModel.ProductId (System.Int32)
```
> Adding detail to exception thrown by projection

- src/AutoMapper/ConfigurationStore.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/Bug/MappingInheritance.cs
- src/UnitTests/MappingInheritance/IncludedMappingShouldInheritBaseMappings.cs
Fixes #762 and #683
Including types will delay the setting of the property maps to Seal().  Seal TypeMap will seal inherited types first, so their inherited type maps will go recursively down to the most inherited map and then back up to the base mapping.  This means order of including Type Maps and IncludeBase no longer matter, they will always seal the most inherited type map and have its property maps persist to the type maps that included it.
AssertConfigIsValid will seal type maps before check property maps.  This will pass all inherited type maps tests without the use of Initialize function.  Actually mapping a type will seal the things it inherits from and put them into the typemapcache, so no need to do Initilize to cache them before hand.
> Fixes Include Seal() Problems #762 #683

- src/AutoMapper/ConfigurationStore.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/Bug/BaseMapWithIncludesAndUnincludedMappings.cs
- src/UnitTests/UnitTests.Net4.csproj
- src/UnitTests/packages.config
Fixes #842, #887, and #893
@jbogard I knew there was a reason GetDerivedTypeFor(Type sourceType) existed.
> Fixed Issues with property map inheritance

- src/AutoMapper/Internal/IMappingOptionsMemberMapper.cs
All member mapping logic is case insensitive now.
Includes PreFix, PostFix, String Replacement, and MapToAttribute.
> Fix for #967

- src/AutoMapper/ConfigurationStore.cs
- src/AutoMapper/IProfileExpression.cs
- src/AutoMapper/Profile.cs
This is what I was talking about with CreateMissingMappings property in #1017
Removes extra if statement with a type pair convention that automatically maps everything.
Took out the get cause it doesn't look that useful with the new implementation, but I could put it back in no problem.
> CreateMissingMappings adds convention

- src/AutoMapper/ConfigurationStore.cs
The current implementation of `ConfigurationStore` causes `ConcurrentDictionary` to lock on all all buckets. This can be a serious perf hit. When you enable the ETW provider `System.Collections.Concurrent.ConcurrentCollectionsEventSource` (or use the Concurrency Visualizer) you can see the following event:
> System.Collections.Concurrent.ConcurrentCollectionsEventSource ConcurrentDictionary acquiring all locks on 32 bucket(s).
This happens when using some "innocent" looking members of the dictionary, such as the `Values` property. You can read more about it in my [blog post](https://arbel.net/2013/02/03/best-practices-for-using-concurrentdictionary/).
> Fix ConcurrentDictionary issues

- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/Profile.cs
- src/UnitTests/Tests/TypeMapFactorySpecs.cs
The goal is to eliminate some of the bugs around people not using the right method for configuring profiles
> Marking Profile as abstract and Configure method abstract

- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/Profile.cs
Right now Profiles are mutable.  You can edit profiles from the class itself, and getting out of configuration mappings.
```
var profile = new MyProfile();
var config = new MapperConfiguration(cfg => cfg.AddProfile(profile));
profile.CreateMap<Foo, Bar>();
```
So like MapperConfiguration is immutable this is a step towards that for profiles.  Can't remove functionality so obsoleted functions that change state, so in 5.0 they can be taken out and profiles can become immutable as part of the configuration.
`IConfiguration.CreateProfile(string profileName);` also has this problem where you can change it outside the configuration level, but that might be a little too anal about this.  You could even say the other CreateProfile has this problem because in the Action you can set a profile …
> Obsolete Mutable Profile calls

- src/UnitTests/MappingInheritance/GenericsAndInterfaces.cs
- src/UnitTests/UnitTests.Net4.csproj
For the new object example it uses proxies, so it fails with a cast error if you use the generic Map< ImplementedClass >, but that's [an old story](https://github.com/AutoMapper/AutoMapper/pull/923) :)
> Passing test; closes #944

- src/AutoMapper/TypeDetails.cs
The build was broken because of [this](https://github.com/AutoMapper/AutoMapper/blob/5222f5cf13bb6dcc8117f6657647e8bec241e510/src/UnitTests/MappingInheritance/GenericsAndInterfaces.cs) test.
Generics and interfaces bug 944
> Fix the generics test

- src/AutoMapper/IConfigurationProvider.cs
- src/AutoMapper/IMapper.cs
- src/AutoMapper/Mapper.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/QueryableExtensions/Extensions.cs
- src/AutoMapper/TypeMapRegistry.cs
- src/UnitTests/StaticMapping.cs
- src/UnitTests/UnitTests.Net4.csproj
Configuration is still readonly, there's no Mapper.Reset. Just Mapper.Initialize. Also restored the queryable extension methods with overloads that grab the static versions.
Downside is I had to keep the explicit implementations of IMapper on Mapper class. To balance that, I put the factory method for CreateMapper on the IConfigurationProvider interface (you can't do `new Mapper()` and start doing stuff, those are static methods).
@lbargaoanu and @TylerCarlson1 this should be a decent compromise, I think.
> Restore some static api

- src/AutoMapper/MapperConfiguration.cs
- src/UnitTests/Bug/InterfaceMultipleInheritance.cs
- src/UnitTests/InterfaceMapping.cs
- src/UnitTests/UnitTests.Net4.csproj
Here is more complicated version, that tries to fix problem that @lbargaoanu noted for original (#1037) version.
This version will iterate interfaces in such order, that more derived interfaces will be before less derived (for IInterfaceBase:IInterfaceDerived, order will be IInterfaceDerived, IInterfaceBase) and iterate interfaces implemented in more derived type before interface implemented in less derived types (so, if we have Base:IInterface1 and Derived:Base,IInterface2 order will be IInterface2, IInterface1).
I was not able found any real example where it may really matter, so probably #1037 will be enough and this is not necessary.
> Added sorting of interfaces (2)

- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/AutoMapper/Configuration/ResolutionExpression.cs
- src/AutoMapper/ConfigurationValidator.cs
- src/AutoMapper/Execution/DelegateBasedResolver.cs
- src/AutoMapper/IMemberConfigurationExpression.cs
- src/UnitTests/Bug/NullableResolveUsing.cs
- src/UnitTests/UnitTests.Net4.csproj
I don't know how this worked before, I just did what made sense :)
This was reported [here](https://github.com/AutoMapper/AutoMapper/issues/1088#issuecomment-181570402).
> When using resolve, infer the type of the resolved value

- src/AutoMapper/IProfileExpression.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/Profile.cs
- src/UnitTests/ExtensionMethods.cs
There is no need to probe, just pass the type containing the extension methods.
I don't know if Queryable matters.
https://github.com/AutoMapper/AutoMapper/pull/1089#issuecomment-181484686
> Extension methods per type

- src/AutoMapper/Configuration/Conventions/CaseInsensitiveName.cs
- src/AutoMapper/Configuration/Conventions/CaseSensitiveName.cs
- src/AutoMapper/Configuration/Conventions/DefaultMember.cs
- src/AutoMapper/Configuration/Conventions/IChildMemberConfiguration.cs
- src/AutoMapper/Configuration/Conventions/IMemberConfiguration.cs
- src/AutoMapper/Configuration/Conventions/IParentSourceToDestinationNameMapper.cs
- src/AutoMapper/Configuration/Conventions/ISourceToDestinationNameMapper.cs
- src/AutoMapper/Configuration/Conventions/MapToAttribute.cs
- src/AutoMapper/Configuration/Conventions/MemberConfiguration.cs
- src/AutoMapper/Configuration/Conventions/NameSplitMember.cs
- src/AutoMapper/Configuration/Conventions/ParentSourceToDestinationNameMapper.cs
- src/AutoMapper/Configuration/Conventions/PrePostfixName.cs
- src/AutoMapper/Configuration/Conventions/ReplaceName.cs
- src/AutoMapper/Configuration/Conventions/SourceToDestinationMapperAttribute.cs
- src/AutoMapper/Configuration/Conventions/SourceToDestinationNameMapperAttributesMember.cs
- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/AutoMapper/Configuration/ResolutionExpression.cs
- src/AutoMapper/ConfigurationValidator.cs
- src/AutoMapper/ConstructorMap.cs
- src/AutoMapper/Execution/DelegateBasedResolver.cs
- src/AutoMapper/ICtorParamConfigurationExpression.cs
- src/AutoMapper/IMemberResolver.cs
- src/AutoMapper/Profile.cs
- src/AutoMapper/PropertyMap.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/QueryableExtensions/Impl/DelegateBasedResolverResolutConverter.cs
- src/AutoMapper/QueryableExtensions/Impl/MemberResolverExpressionResultConverter.cs
- src/AutoMapper/TypeMapFactory.cs
Now Have ExpressionBasedResolver to distinguish the two resolver types
> Add DestinationType back into resolving member info conventions. Part 2

- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/TypeMap.cs
- src/AutoMapper/TypePair.cs
[Before](https://cloud.githubusercontent.com/assets/4517428/13281693/e85e1e18-daed-11e5-8920-7def940347d8.png) & [after](https://cloud.githubusercontent.com/assets/4517428/13282395/70fb9310-daf1-11e5-941d-65d0ece6f158.png).
We could try the same for ResolutionContext and ResolutionResult. It's true that the ResolutionContext is too big right now.
[The test project](https://github.com/lbargaoanu/AutoMapperBenchmark).
> Make TypePair a struct

- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs
- src/UnitTests/Projection/NullableItemsTests.cs
- src/UnitTests/Projection/ProjectionTests.cs
- src/UnitTests/Query/SourceInjectedQuery.cs
- src/UnitTests/UnitTests.Net4.csproj
Hi, this is a simplified version of #852, this time skipping the gratuitous refactoring (and also some of the side issues, which I'll treat separately).
Basically, this PR: 
* Moves the `AssignableExpressionBinder` down the list of binders, so that it allows other binding behaviours a chance to do their stuff when projecting like to like
* Fixes up `EnumerableExpressionBinder` to add null-guards when `config.AllowNullCollections` is set to true - nulls were previously always copied over by `AssignableExpressionBinder`
> Small changes to expression-binding behaviour II

- src/AutoMapper/IMapper.cs
- src/AutoMapper/Mapper.cs
- src/AutoMapper/Mappers/EnumerableMapperBase.cs
- src/AutoMapper/Mappers/TypeMapObjectMapperRegistry.cs
- src/AutoMapper/ResolutionContext.cs
[Before](https://cloud.githubusercontent.com/assets/4517428/13432667/4e3990e4-dfd7-11e5-9531-821a4f685911.png) & [after](https://cloud.githubusercontent.com/assets/4517428/13432666/4e31b73e-dfd7-11e5-9dde-73b812268fd4.png).
[The test project](https://github.com/lbargaoanu/AutoMapperBenchmark).
> Reuse the ResolutionContext for properties and enumerable items

- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/AutoMapper/IMemberConfigurationExpression.cs
- src/UnitTests/Bug/NullSubstituteType.cs
- src/UnitTests/UnitTests.Net4.csproj
I don't know if this is the right fix, but #1183 seems reasonable.
> Make the null substitute type safe

- src/AutoMapper/Mappers/EnumerableMapperBase.cs
- src/UnitTests/ArraysAndLists.cs
> Use the runtime type of the source object when mapping collections

- src/AutoMapper/ConstructorParameterMap.cs
- src/AutoMapper/ICtorParamConfigurationExpression.cs
- src/UnitTests/IMappingExpression/ForCtorParam.cs
This adds a failing test for #1023. If a property
```
public int Bar { get; set; }
```
is added to the `SourceFoo` type, and the setup is updated accordingly,
the test passes, but I would like it to work without that property.
> Faling test for #1023

- src/AutoMapper/Mappers/ExpressionMapper.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/QueryableExtensions/Impl/CustomProjectionExpressionBinder.cs
Can't just go replace all parameters.  What about sublambdas.  You must tell it what it must replace.
ProjectTo parameter replacer replaces sub lambdas. as well as the base lambda.
Also since most are using lambdas to do parameter replacement visitor, the ReplaceParameters extension method https://github.com/AutoMapper/AutoMapper/pull/1211#discussion_r58068857 would be a good choice to use here as well.
> Flatten nested children using ProjectTo

- src/AutoMapper/AutoMapperMappingException.cs
- src/AutoMapper/ConstructorMap.cs
- src/AutoMapper/ConstructorParameterMap.cs
- src/AutoMapper/Mapper.cs
- src/AutoMapper/Mappers/ExpressionMapper.cs
- src/AutoMapper/PropertyMap.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/QueryableExtensions/Impl/CustomProjectionExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/MemberResolverExpressionResultConverter.cs
- src/AutoMapper/ResolutionContext.cs
- src/AutoMapper/TypeMap.cs
Moves the Expression creation to another class, and then replaces parameters at the PropertyMap level.
Made some extension methods as well to help things be more readable.
Property map will convert parameters to Source and Destination type, but the expression generated will assume the types are already set correctly.  What's good about this that you can convert the same expression over for the TypeMap.  You can just replace the parameters with variables you set when generating the TypeMap expression, and not have to re-write the PropertyMap Expression generating code.
Only real problems having right now are with struct's, so what probably needs to be done is convert the expressions to use ref if ValueType, so can pass object over to be set correctly, or something like that.
> [WIP] Remove PropertyMap Casting

- src/AutoMapper/ConstructorParameterMap.cs
- src/AutoMapper/Mappers/ArrayMapper.cs
- src/AutoMapper/Mappers/AssignableMapper.cs
- src/AutoMapper/Mappers/CollectionMapper.cs
- src/AutoMapper/Mappers/ConvertMapper.cs
- src/AutoMapper/Mappers/DictionaryMapper.cs
- src/AutoMapper/Mappers/DynamicMappers.cs
- src/AutoMapper/Mappers/EnumMapper.cs
- src/AutoMapper/Mappers/EnumerableMapper.cs
- src/AutoMapper/Mappers/EnumerableToDictionaryMapper.cs
- src/AutoMapper/Mappers/ExplicitConversionOperatorMapper.cs
- src/AutoMapper/Mappers/ExpressionMapper.cs
- src/AutoMapper/Mappers/FlagsEnumMapper.cs
- src/AutoMapper/Mappers/HashSetMapper.cs
- src/AutoMapper/Mappers/ImplicitConversionOperatorMapper.cs
- src/AutoMapper/Mappers/MapperRegistry.cs
- src/AutoMapper/Mappers/MultidimensionalArrayMapper.cs
- src/AutoMapper/Mappers/NameValueCollectionMapper.cs
- src/AutoMapper/Mappers/NullableMapper.cs
- src/AutoMapper/Mappers/NullableSourceMapper.cs
- src/AutoMapper/Mappers/PrimitiveArrayMapper.cs
- src/AutoMapper/Mappers/ReadOnlyCollectionMapper.cs
- src/AutoMapper/Mappers/StringDictionaryMapper.cs
- src/AutoMapper/Mappers/StringMapper.cs
- src/AutoMapper/Mappers/TypeConverterMapper.cs
- src/UnitTests/Bug/ExpressionMapping.cs
- src/UnitTests/IMappingExpression/NonGenericProjectEnumTest.cs
Want to also point out INullableSourceMapper changed a bit cause there's no reason to null check and do the context assert nulls, because the `Nullable<T>` is a stuct, thus it can't be null and the check isn't needed.  Also it's much simplified to read.
Also make sure when to check nullable to null they are the same types so that double? -> int won't be tried and it will say Un-mapped types instead of can't cast double? to int.
Still going to go through a few more mappers to convert them to IObjectMapExpression.
> Finish IObjectMapExpression conversions

- src/AutoMapper/MapperConfiguration.cs
Issue with AutoMapper.Collection it's going to need to call IConfiguration.ResolveTypeMap which is done on seal now.  The problem is the thing gets sealed without the functions to actively run ResolveTypeMaps,  therefore I get exceptions.
> Make seal last and move newing up create map functions before do config and seal.

- src/AutoMapper/Configuration/MapperConfigurationExpression.cs
- src/AutoMapper/IConfiguration.cs
- src/AutoMapper/IConfigurationProvider.cs
- src/AutoMapper/Mapper.cs
- src/AutoMapper/MapperConfiguration.cs
- src/UnitTests/SeparateConfiguration.cs
- src/UnitTests/UnitTests.Net4.csproj
This allows you to have the configuration expression passed around and modified, before you then pass it to the MapperConfiguration for consumption.
> Configuration expression separating

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/IObjectMapper.cs
- src/AutoMapper/Mappers/ArrayMapper.cs
- src/AutoMapper/Mappers/AssignableMapper.cs
- src/AutoMapper/Mappers/CollectionMapper.cs
- src/AutoMapper/Mappers/ConvertMapper.cs
- src/AutoMapper/Mappers/DictionaryMapper.cs
- src/AutoMapper/Mappers/DynamicMappers.cs
- src/AutoMapper/Mappers/EnumMapper.cs
- src/AutoMapper/Mappers/EnumerableMapper.cs
- src/AutoMapper/Mappers/EnumerableToDictionaryMapper.cs
- src/AutoMapper/Mappers/ExplicitConversionOperatorMapper.cs
- src/AutoMapper/Mappers/ExpressionMapper.cs
- src/AutoMapper/Mappers/FlagsEnumMapper.cs
- src/AutoMapper/Mappers/HashSetMapper.cs
- src/AutoMapper/Mappers/ImplicitConversionOperatorMapper.cs
- src/AutoMapper/Mappers/MultidimensionalArrayMapper.cs
- src/AutoMapper/Mappers/NameValueCollectionMapper.cs
- src/AutoMapper/Mappers/NullableMapper.cs
- src/AutoMapper/Mappers/NullableSourceMapper.cs
- src/AutoMapper/Mappers/PrimitiveArrayMapper.cs
- src/AutoMapper/Mappers/ReadOnlyCollectionMapper.cs
- src/AutoMapper/Mappers/StringDictionaryMapper.cs
- src/AutoMapper/Mappers/StringMapper.cs
- src/AutoMapper/Mappers/TypeConverterMapper.cs
- src/Benchmark/Program.cs
@TylerCarlson1 thoughts? The idea is to expand the expression mappers to be able to examine config and pre-wire some of the decisions they make. Source value/collection null etc.
Also makes the actual mapping part a little more obvious, it's just a LINQ select/toarray, surrounded by expressions that have the extra juice.
> Array mapper improvements

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/UnitTests/TypeConverters.cs
As in #1330. I could swear this used to work :)
Whitespace in UnitTests/TypeConverters.cs. The test is at the top.
> Allow overriding the built in object mapper with a custom type converter

- src/AutoMapper/Mappers/ArrayMapper.cs
ToArray has to double enumerate.
You could go a bit further and make array mapper pure expression based, and from that you can use source.Length in cases of array instead of relying on source.Count() which will save you time in array to array mappings.  That can be saved for a later PR I guess
> Better Array Mappings

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/ExpressionExtensions.cs
This time I think I got it.  Seems to work on all maps including sub property null checks.  Because when the expression is created it takes it out, and when replace parameters it won't have that null check.
> Remove null checks from map when src allready checked

- src/AutoMapper.Net4/AutoMapper.Net4.csproj
- src/AutoMapper/AssemblyInfo.cs
- src/AutoMapper/project.json
- src/Benchmark/BenchEngine.cs
- src/Benchmark/Program.cs
I got about 40%. [Before](https://cloud.githubusercontent.com/assets/4517428/16297527/da2b7d18-3939-11e6-9197-4dc640baf460.png) and [after](https://cloud.githubusercontent.com/assets/4517428/16297528/da31cbdc-3939-11e6-9e80-b673f8a7ab1b.png).
> Try to skip the security check

- src/AutoMapper/AssemblyInfo.cs
- src/Benchmark/BenchEngine.cs
- src/Benchmark/Program.cs
You wouldn't think this is so complicated. Third time's a charm :)
About @TylerCarlson1's version.
Stopwatch ticks are different from DateTime.Ticks. Each tick in the DateTime.Ticks value represents one 100-nanosecond interval. Each tick in the ElapsedTicks value represents the time interval equal to 1 second divided by the Frequency.
https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.elapsedticks(v=vs.110).aspx
> Measure only the map calls & remove unneeded attributes

- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/IntegrationTests.Net4/IntegrationTests.Net4.csproj
- src/IntegrationTests.Net4/NavigationPropertySO.cs
closes #1352
a null check and a passing test
MaxDepth works as expected; I believe the only way to break the cycle is to introduce incompatible initializations
> ProjectTo stack overflow

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/Constructors.cs
skip property mapping only when a matching constructor was really used for the destination. 
The initial implementation was kind of silly :blush:. But this one might be too much considering the purpose. So maybe forget the whole thing. It would mean that if you have a setter, it will be called, even if it was already mapped though the constructor.
> Fixes #1417

- src/AutoMapper/ExpressionExtensions.cs
- src/AutoMapper/Mappers/ArrayMapper.cs
- src/Benchmark/FlatteningMapper.cs
Generate better enumeration code for concrete types. Avoid allocations and interface dispatch by using the enumerator pattern for collections and a for loop for arrays.
> Enumerators

- src/AutoMapper/Mappers/DictionaryMapper.cs
#1418 and #1518 are the same issue (as the numbers clearly suggest).
#1520 fixes both. 
#1430 is not needed.
> ExpandoObject is a dictionary and should be mapped as such

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/UnitTests/FillingExistingDestination.cs
if a destination was passed, map to destination subobjects by default, no UseDestinationValue necessary
fixes #1486
> Map to existing object

- src/AutoMapper/TypeMap.cs
- src/UnitTests/MappingInheritance/ShouldInheritBeforeAndAfterMap.cs
Because it's easy &trade;
@jbogard Just close it if you think this needs more consideration.
> Don't allow duplicate After/Before Map registrations

- src/AutoMapper/AutoMapperConfigurationException.cs
1. Fixes #1547
1. Ran all UnitTests.Net4: all succeeded, apart from 5 skipped
1. IntegrationTests.Net4 not ran: they were somehow hanging in VS2015, right at the beginning
> Break long line in AutoMapperConfigurationException

- src/AutoMapper/Execution/DelegateFactory.cs
- src/AutoMapper/ExpressionExtensions.cs
- src/UnitTests/Bug/NullableDateTime.cs
Fixes #1552. Closes #1550.
I think the root cause of the nullable issues was the fact that the node type was changed in flight, so to speak, without knowing it's safe to do so. It should be safe for the initial expression.
@jbogard This assumes the member accesses visited are really executed, so when any is null, return null. I think this is correct after the new checks you made recently. Of course it could be made more complicated to detect whether the members were really accessed, but with those checks in place, I see no point. If you want to get rid of the checks, the story changes.
> Add a null guard instead of rewriting each node

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/ExpressionExtensions.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/Mappers/CollectionMapper.cs
- src/AutoMapper/ResolutionContext.cs
- src/UnitTests/Bug/DuplicateValuesBug.cs
That thing about initialDestination in CreateMapper lambda was a little too hardcore for me. But what can you do? :)
This doesn't do much. The good news is that the deep types test runs three times faster. The bad new is that the generated code looks pretty bad. Probably one reason I had such a hard time with that bug I mentioned.
> Inline the easy cases

- src/AutoMapper/Configuration/MapperConfigurationExpression.cs
- src/AutoMapper/IConfiguration.cs
- src/AutoMapper/IMapperConfigurationExpression.cs
- src/AutoMapper/IProfileExpression.cs
- src/UnitTests/AssemblyScanning.cs
- src/UnitTests/UnitTests.Net4.csproj
Allow scanning of assemblies for profiles. Can load via:
- Assembly
- Assembly name (string, using AssemblyName internally)
- Type from assembly containing profiles
> Profile scanning

- src/AutoMapper/Execution/ProxyGenerator.cs
- src/UnitTests/Internal/CreateProxyThreading.cs
- src/UnitTests/UnitTests.Net4.csproj
Fixes #1562.
It's a threading issue. When multiple threads are in GetOrAdd, the same proxy will be generated twice and fail the unique type name check.
> Proxy generator

- src/AutoMapper/IObjectMapper.cs
- src/UnitTests/Mappers/CustomMapperTests.cs
It's true that anybody can write this, but I thought it might be nice to have something built in.
> Base class for simple object mappers that don't want to use expressions.

- src/AutoMapper/TypeMap.cs
- src/UnitTests/Internal/NullConstructorParameter.cs
- src/UnitTests/UnitTests.Net4.csproj
Pedantic? :)
There is no need to explicitly check for null. Fixes #1596. Closes #1597.
> Don't fail when the parameter name is null

- src/AutoMapper/ICtorParamConfigurationExpression.cs
- src/UnitTests/IMappingExpression/ForCtorParam.cs
We already have the ability to resolve constructor parameters using `Func<TSource, object>`, but we can't access `ResolutionContext` there (as it is possible with property mappings). There is sufficient infrastructure for this, so the only change that was required was to provide correct overload of `ResolveUsing`.
> ResolveUsing overload with ResolutionContext for ctor params

- src/AutoMapper/Configuration/Conventions/SourceToDestinationNameMapperAttributesMember.cs
- src/AutoMapper/TypeMap.cs
Fixed memory leaks caused when initializing Automapper multiple times on
the same thread/appdomain.
Made Cache in SourceToDestinationNameMapperAttributesMember non-static.
Removed usage of ConcurrentBag in TypeMap, it now uses List<T>.
Closes #1691
> Fixed memory leaks

- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/AutoMapper/IMemberConfigurationExpression.cs
It was needed a couple of times.
> Expose the destination member

- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/TypeExtensions.cs
Fixes #1748.
I don't see an easy way to test for this.
> Consider VB closures

- src/AutoMapper/Configuration/Conventions/SourceToDestinationNameMapperAttributesMember.cs
- src/AutoMapper/Execution/DelegateFactory.cs
- src/AutoMapper/Profile.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/QueryableExtensions/IExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/AssignableExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/CustomProjectionExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/MappedTypeExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/NullableExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/StringExpressionBinder.cs
I reviewed usage of ConcurrentDictionary and replaced it with LockingConcurrentDictionary or Dictionary.
Did a little more in SourceToDestinationNameMapperAttributesMember. Sorry for the whitespace in Profile.cs VS did it :)
> Replace ConcurrentDictionary

- src/AutoMapper/ICtorParamConfigurationExpression.cs
- src/UnitTests/IMappingExpression/ForCtorParam.cs
Before, all attempts at mapping constructor parameters for classes that
did not have a constructor defined, or where no defined constructor had
a parameter with that name, would throw an exception with a pretty poor
uninformative exception message.
These scenarios are now considered valid mapping configurations, as long
as the stuff that's needed to actually perform a mapping is also
configured.
Fixes #1528
> Make constructor mapping a little more lenient

- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/IMappingExpression.cs
- src/UnitTests/MappingInheritance/ShouldSupportOnlyDestinationTypeBeingDerived.cs
Skipped generics for simplicity. From #1776.
> Check the destination type override to be a derived type

- src/AutoMapper/Configuration/MapperConfigurationExpression.cs
- src/AutoMapper/IMapperConfigurationExpression.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/Mappers/MapperRegistry.cs
- src/UnitTests/Bug/ConvertMapperThreading.cs
- src/UnitTests/Mappers/CustomMapperTests.cs
- src/UnitTests/UnitTests.Net4.csproj
> Avoid static state

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/UnitTests/Bug/PreserveReferencesSameDestination.cs
I'm not sure about that check, no tests fail :)
Fixes #1794.
> Preserve references bug

- src/AutoMapper/MapperConfiguration.cs
- src/UnitTests/TypeConverters.cs
Maybe this would make sense in other places too, but the cases I saw before were similar.
> Match on requested types if runtime types don't match; fixes #1865

- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/UnitTests/Bug/CannotProjectStringToNullableEnum.cs
- src/UnitTests/UnitTests.Net4.csproj
The order of the list of `IExpressionBinders` in `ExpressionBuilder.cs` is important because the first matching `ExpressionBinder` is selected.  When a custom expression binder is provided in the user's configuration, this should be used in preference to any of the built-in binders.  Prior to this fix the NullableExpresisonBinder would indicate a match if the destination type was of type `System.Nullable<>`  Fixes #1879 
Also added a unit test to demonstrate the bug.
> Correct order of ExpressionBinders

- src/AutoMapper/ProfileMap.cs
- src/UnitTests/ReverseMapping.cs
Currently, `ReverseMap` and open generics don't work together - the new test in this commit would fail with a 'Missing type map configuration' exception. This fixes that by including reverse maps when configuring closed generic maps.
> Use ReverseTypeMaps when configuring closed generic TypeMaps

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/ResolutionContext.cs
- src/UnitTests/Bug/OneSourceWithMultipleDestinationsAndPreserveReferences.cs
- src/UnitTests/UnitTests.Net4.csproj
Fixes #1892. Closes #1894.
I guess it's a breaking change, but nobody should be using InstanceCache anyway. We could make it internal, or even private (private seems best). Funny enough, I wasn't able to make out parameters work, and not for lack of trying. It worked in a simple test, but not in AM.
I took GetHashCode from System.Tuple. I guess it's close to the idea you used in TypePair. We should have a helper to be used everywhere. It's not in the framework yet I believe. I don't think we need to cache the hash code when the fields are read-only. Tuple doesn't. That saves the field and avoids computing it when it's not needed (granted, that's just a few instructions).
> Preserve references

- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/AutoMapper/IMemberConfigurationExpression.cs
- src/UnitTests/Bug/ForAllMembersAndDoNotUseDestinationValue.cs
I think this should have been removed when we changed the default. I was tempted to use it for #1918. But of course, it doesn't do anything.
> UseDestinationValue is now false by default

- src/AutoMapper/ProfileMap.cs
- src/UnitTests/DynamicMapping.cs
Fixes #1931. I guess primitive types, string, decimal would make sense too. It might break some people, but I think we should exclude them.
> Exclude more system base types

- src/AutoMapper/LockingConcurrentDictionary.cs
- src/AutoMapper/MapperConfiguration.cs
- src/UnitTests/Bug/MultiThreadingIssues.cs
I guess we cannot have a single global lock. The right granularity seems to be per type pair. But this can be tricky. Hopefully it doesn't matter much in the usual case because everything is already in the cache. Creating maps on the fly is more complicated.
> Concurrency

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/IObjectMapper.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/Mappers/ArrayMapper.cs
- src/AutoMapper/Mappers/AssignableMapper.cs
- src/AutoMapper/Mappers/CollectionMapper.cs
- src/AutoMapper/Mappers/ConvertMapper.cs
- src/AutoMapper/Mappers/DictionaryMapper.cs
- src/AutoMapper/Mappers/DynamicMappers.cs
- src/AutoMapper/Mappers/EnumMapper.cs
- src/AutoMapper/Mappers/EnumerableMapper.cs
- src/AutoMapper/Mappers/EnumerableToDictionaryMapper.cs
- src/AutoMapper/Mappers/ExplicitConversionOperatorMapper.cs
- src/AutoMapper/Mappers/ExpressionMapper.cs
- src/AutoMapper/Mappers/FlagsEnumMapper.cs
- src/AutoMapper/Mappers/HashSetMapper.cs
- src/AutoMapper/Mappers/ImplicitConversionOperatorMapper.cs
- src/AutoMapper/Mappers/MultidimensionalArrayMapper.cs
- src/AutoMapper/Mappers/NameValueCollectionMapper.cs
- src/AutoMapper/Mappers/NullableSourceMapper.cs
- src/AutoMapper/Mappers/ReadOnlyCollectionMapper.cs
- src/AutoMapper/Mappers/StringDictionaryMapper.cs
- src/AutoMapper/Mappers/StringMapper.cs
- src/AutoMapper/Mappers/TypeConverterMapper.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/Mappers/CustomMapperTests.cs
I think we fixed a few issues around TypeMapRegistry.GetTypeMap and now it's not used much.
> We usually want ResolveTypeMap, not TypeMapRegistry.GetTypeMap

- src/AutoMapper/MapperConfiguration.cs
- src/UnitTests/CollectionMapping.cs
> Use the runtime type for the destination too

- src/AutoMapper/AdvancedConfiguration.cs
- src/AutoMapper/Configuration/MapperConfigurationExpression.cs
- src/UnitTests/AssemblyScanning.cs
- added tests for scanning internal profiles
- determine the loading strategy based on "ScanForInternalProfiles" property
- modified the current implementation so that the scanning is done later in the process, and not immediately (more user friendly)
Fixes #2063.
> AddProfiles() includes internal types when scanning assemblies

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/Internal/ExpressionFactory.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/Mappers/ArrayMapper.cs
- src/AutoMapper/Mappers/ConvertMapper.cs
- src/AutoMapper/Mappers/EnumToEnumMapper.cs
- src/AutoMapper/Mappers/EnumToUnderlyingTypeMapper.cs
- src/AutoMapper/Mappers/FlagsEnumMapper.cs
- src/AutoMapper/Mappers/Internal/CollectionMapperExpressionFactory.cs
- src/AutoMapper/Mappers/MultidimensionalArrayMapper.cs
- src/AutoMapper/Mappers/NameValueCollectionMapper.cs
- src/AutoMapper/Mappers/NullableSourceMapper.cs
- src/AutoMapper/Mappers/StringMapper.cs
- src/AutoMapper/Mappers/UnderlyingTypeToEnumMapper.cs
- src/UnitTests/NullBehavior.cs
Fixes #2102 and some part of #1987.
> Null checks

- src/AutoMapper/ConfigurationValidator.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/IConfigurationProvider.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/BidirectionalRelationshipsWithoutPR.cs
- src/UnitTests/Bug/DuplicateValuesBugWithoutPR.cs
- src/UnitTests/Bug/OneSourceWithMultipleDestinationsWithoutPR.cs
- src/UnitTests/Bug/WithoutPreserveReferencesSameDestination.cs
- src/UnitTests/MaxDepthTests.cs
- src/UnitTests/ReverseMapWithPreserveReferences.cs
- src/UnitTests/ReverseMapWithoutPreserveReferences.cs
- src/UnitTests/UnitTests.Net4.csproj
This affects the complex types benchmark. I guess I should modify it to prevent that. It might break some people, but I think we should remove Configuration.GetMappers().
> Detect cycles at config time and set PreserveReferences accordingly

- src/AutoMapper/Configuration/PrimitiveExtensions.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/Internal/ExpressionFactory.cs
- src/AutoMapper/Mappers/HashSetMapper.cs
- src/UnitTests/Mappers/NameValueCollectionMapperTests.cs
- src/UnitTests/NullBehavior.cs
> Allow null colections

- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/QueryableExtensions/ExpressionRequest.cs
- src/AutoMapper/QueryableExtensions/Impl/SourceInjectedQueryProvider.cs
- src/AutoMapper/QueryableExtensions/ProjectionExpression.cs
- src/UnitTests/Projection/MapFromTest.cs
The typed version of ``GetMapExpression()`` has ``params MemberInfo[]``. Make certain the untyped version creates an empty array otherwise ``ExpressionRequest`` crashes in ctor.
> Fix ExpressionBuilder GetMapExpression behaviour

- src/AutoMapper/Configuration/PathConfigurationExpression.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/IPathConfigurationExpression.cs
- src/AutoMapper/PathMap.cs
- src/UnitTests/ForPath.cs
Should really have done this with 6.1.0, whoops.
Allow you to ignore a path:
```csharp
cfg =>
{
cfg.CreateMap<TimesheetModel, TimesheetViewModel>()
.ForMember(d=>d.Contact, o=>o.MapFrom(s=>s.ContactNavigation.Id))
.ReverseMap()
.ForPath(s => s.ContactNavigation.Id, opt => opt.Ignore());
}
```
> Allow ignores on reverse map paths

- src/AutoMapper/TypeMap.cs
- src/UnitTests/MappingInheritance/SourceValidationWithInheritance.cs
Fixes #2172. This won't work for more complicated expressions. If you feel it's inconsistent, just close it.
> Allow simple MapFrom-s to pass validation

- src/AutoMapper/Mappers/ExpressionMapper.cs
- src/AutoMapper/QueryableExtensions/Impl/QueryMapperHelper.cs
- src/AutoMapper/QueryableExtensions/Impl/SourceInjectedQueryProvider.cs
- src/UnitTests/Query/SourceInjectedQuery.cs
Conventions can't use UseAsDataSource without calling map first because when generate expressions it doesn't try to resolve type map, just find if it exists.
> Use Resolve instead of Find for expression generation

- src/AutoMapper/ConstructorMap.cs
- src/AutoMapper/ConstructorParameterMap.cs
- src/AutoMapper/Execution/DelegateFactory.cs
- src/AutoMapper/Execution/ExpressionBuilder.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/Internal/ExpressionFactory.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/Mappers/Internal/CollectionMapperExpressionFactory.cs
- src/AutoMapper/Mappers/NullableSourceMapper.cs
Making the TypeMapPlanBuilder only build type map expressions and nothing else. Broke out other concerns to a separate static class we can do `using static` with.
> Type map plan builder refactor

- src/AutoMapper/Execution/ExpressionBuilder.cs
- src/AutoMapper/Internal/ExpressionFactory.cs
This is just a minor refactoring, currently ``ContextMap`` uses ``.First`` with the method name to get the proper methodinfo, this depends on the order of methods in the ``ResolutionContext`` class, there are already two methods called ``Map``, now it uses the ``Method`` idea from ``ExpressionFactory``, this should prevent suprises when refactoring ``ResolutionContext``.
I added another of the ``Method`` methods to the ``ExpressionFactory`` to support non-static methods.
No extra tests were added as this method is called in many unit tests, if you want to see how it fails, use the old code and swap the ``Map`` methods in ``ResolutionContext``, I get ~150 failed tests then.
> Add static ResolutionContext.Map MethodInfo field in ExpressionBuilder

- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/ProfileMap.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/UnitTests/Bug/MultiThreadingIssues.cs
Fixes #2206.
I think there is too much code that tries to be thread safe. The configuration code doesn't need to be thread safe, except when creating type maps on the fly. A global lock should solve it. Of course, there is less concurrency, but only those cases should be affected. I believe it's a good compromise between performance and code complexity.
> Introduce a global lock when creating type maps on the fly

- src/AutoMapper/MapperConfiguration.cs
I've tried to do the same as in Resolve, lock on the map, but that is meaningless here because it's always a new map, so nothing gets locked. What can happen here is that two threads create the same map. I'm not sure that's bad. I'd say it isn't. I don't see an easy way out here. A different cache for the on the fly maps would work I believe. But I'd rather wait for someone to report a problem with it.
> It's always a new map, locking on it doesn't help

- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/AutoMapper/Configuration/PathConfigurationExpression.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/ReverseMapping.cs
Fixes #2199.
Kind of convoluted. Maybe it's the implementation, but I'd say it's the requirements.
- ForPath should make the first member pass validation
- ignoring the first member ignores all the paths that start with it
- an explicit ForPath should override the ignored first member
Maybe we should give up a few of these :)
> Ignore member paths

- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/BidirectionalRelationshipsWithoutPR.cs
- src/UnitTests/UnitTests.csproj
> We have to set everything in the plan, we don't get a second chance

- src/UnitTests/TypeConverters.cs
All I did with that #if was to skip the test :) The problem is that without AppDomains, the CLR cannot find the test assembly. Load contexts and stuff. It should be OK now.
> Help the CLR find the assemblies it needs

- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/AutoMapper/IMemberConfigurationExpression.cs
- src/UnitTests/Bug/ConditionBug.cs
Added an overload to PreCondition that had both TSource and ResolutionContext as parameters.
Closes #2251.
> Add PreCondition overload that takes source and ResolutionContext as parameters

- src/AutoMapper/Configuration/Internal/PrimitiveHelper.cs
- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/Configuration/PrimitiveExtensions.cs
- src/UnitTests/IgnoreAllTests.cs
I want to Ignore a property mapping even if currently there is no equivalent property in the source type to ignore. I want to Ignore it in destination type permanently, now and in the future. so I put an `IgnoreMap` attribute on the destination property
> Don't throw ArgumentOutOfRangeException when there is no reverse property to IgnoreMap. issue #2266

- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/AutoMapper/Configuration/PathConfigurationExpression.cs
- src/AutoMapper/IMappingExpression.cs
- src/AutoMapper/IPathConfigurationExpression.cs
- src/AutoMapper/PathMap.cs
- src/AutoMapper/PropertyMap.cs
- src/UnitTests/ForPath.cs
Fixes #2298. It's different, but the way I see it, the regular conditions should work the same way too :) If we had [this](https://github.com/dotnet/csharplang/issues/258) we could have it both ways. I could add a Deconstruct method now, but the usage syntax is clumsy.
> Add ForPath conditions

- src/AutoMapper/XpressionMapper/Extensions/MapperExtensions.cs
- src/AutoMapper/XpressionMapper/XpressionMapperVisitor.cs
Fixes #2378 
The type check in XpressionMapperVisitor.VisitBinary was redundant - the exception will only be thrown if type checks in XpressionMapperVisitor.FindDestinationFullName (Resource.expressionMapValueTypeMustMatchFormat) are removed.
> Fix for #2378 Expression mapping with coalesce operator is extremely slow or just hangs up.

- docs/Inline-Mapping.md
- docs/index.rst
- src/AutoMapper/Configuration/IProfileConfiguration.cs
- src/AutoMapper/ConfigurationValidator.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/IConfigurationProvider.cs
- src/AutoMapper/IMappingOperationOptions.cs
- src/AutoMapper/IProfileExpression.cs
- src/AutoMapper/Mapper.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/MappingOperationOptions.cs
- src/AutoMapper/Profile.cs
- src/AutoMapper/ProfileMap.cs
- src/AutoMapper/ResolutionContext.cs
- src/AutoMapper/TypeMap.cs
- src/AutoMapper/TypePair.cs
- src/UnitTests/AutoMapperSpecBase.cs
- src/UnitTests/Bug/ExpressionMapping.cs
- src/UnitTests/Bug/MissingMapping.cs
- src/UnitTests/Bug/NullableToInvalid.cs
- src/UnitTests/CollectionMapping.cs
- src/UnitTests/ConfigurationValidation.cs
- src/UnitTests/DynamicMapping.cs
- src/UnitTests/ReverseMapping.cs
So far moved the dynamic mapping out of conventions and into a last-resort-mapping step. Conventions had their issues of being in a weird place in the mapping pipeline, this moves it to a more last-resort step.
> Inline config and auto-auto-mapping

- src/AutoMapper/AutoMapper.csproj
- src/AutoMapper/Configuration/Conventions/SourceToDestinationNameMapperAttributesMember.cs
- src/AutoMapper/Configuration/ITypeMapConfiguration.cs
- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/IConfigurationProvider.cs
- src/AutoMapper/LockingConcurrentDictionary.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/ProfileMap.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/TypeMap.cs
- src/AutoMapper/TypeMapFactory.cs
- src/AutoMapper/TypePair.cs
- src/UnitTests/Bug/BaseMapWithIncludesAndUnincludedMappings.cs
- src/UnitTests/Bug/ExpressionMapping.cs
- src/UnitTests/DynamicMapping.cs
- src/UnitTests/Projection/ProjectTest.cs
- src/UnitTests/Query/SourceInjectedQuery.cs
- src/UnitTests/Tests/TypeMapFactorySpecs.cs
- src/UnitTests/XpressionMapperTests.cs
> Moving inline map creation back to inside type map resolving

- src/AutoMapper/ConstructorMap.cs
- src/UnitTests/Projection/MoreExplanatoryExceptionTests.cs
While defining a new mapping between two classes, I was getting a mysterious `Can't resolve this to Queryable Expression` error message. The message was not meaningful enough so I had to debug AutoMapper to understand what the problem was. I simply had to tell AutoMapper which constructor had to be used...
This PR intends to generate a more explanatory error message.
> Better error message when the creation of the instantiation expression fails

- src/AutoMapper/AutoMapper.csproj
- src/AutoMapper/Execution/DelegateFactory.cs
- src/AutoMapper/Mappers/Internal/CollectionMapperExpressionFactory.cs
- src/UnitTests/CollectionMapping.cs
- src/UnitTests/Dictionaries.cs
This fixes the newly introduced issue of casting collection types. I didn't think forcing everyone to use `UseDestinationValue` was a good solution, this change centers around the interfaces and the concrete types are only used for instantiation.
> Collection bug

- src/AutoMapper/AutoMapper.csproj
- src/AutoMapper/Execution/DelegateFactory.cs
- src/AutoMapper/Execution/ExpressionBuilder.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/IConfigurationProvider.cs
- src/AutoMapper/IMapper.cs
- src/AutoMapper/Internal/ReflectionHelper.cs
- src/AutoMapper/Mapper.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/Mappers/MultidimensionalArrayMapper.cs
- src/AutoMapper/PropertyMap.cs
- src/AutoMapper/ReflectionExtensions.cs
- src/AutoMapper/ResolutionContext.cs
- src/AutoMapper/TypePair.cs
- src/IntegrationTests/Inheritance/QueryableInterfaceInheritanceIssue.cs
- src/UnitTests/FillingExistingDestination.cs
- src/UnitTests/Mappers/CustomMapperTests.cs
- src/UnitTests/Mappers/StringDictionaryMapperTests.cs
- src/UnitTests/NullBehavior.cs
Fixes #2466.
The diff for FillingExistingDestination.cs is mostly whitespace. The new test is at the top.
If I change the default for Inline in PropertyMap, all tests pass, except the one assuming the default is true.
> Make mapping at runtime closer to inline mapping

- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
> Ignore properties that are not expanded

- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
I don't know how to correctly cite a license (#2235), but I can provide the current (improved) code.
It now (since Jan 2017, actually) only inserts a null-check, if some access isn't safe, and not in every possible spot like a madman. Thus, it just produces much less overhead.
I just copied the code (again), used your `LockingConcurrentDictionary`, switched to some reflection extensions (.NET 4.0?), and checked if all the tests still went green (they did).
> Update copy of NeinLinq.NullsafeQueryRewriter

- src/AutoMapper/Execution/ProxyGenerator.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
https://stackoverflow.com/questions/48288950/autmapper-projectto-fails-with-firstordefault
> Let clause : explicitly generate just the properties we need

- src/AutoMapper/IObjectMapper.cs
- src/UnitTests/Mappers/CustomMapperTests.cs
A breaking change, but it seems harmless.
> Simple object mapper : When the destination object is null, it can be useful to know its type

- src/AutoMapper/Mappers/ExpressionMapper.cs
- src/AutoMapperSamples.EF/EffortQueryTests.cs
- src/AutoMapperSamples.OData/ODataQueryTests.cs
- src/AutoMapperSamples.OData/OrdersController.cs
Fix for #2520
The ExpressionMapper has the following bug.
In ExpressionMapper.VisitBinary, it compares the types of the two expressions.
If one is of type string and the other is not, it adds a "ToString()" to the expression.
However, it does not check for the "null Constant".
Therefore, the OData query of ODataQueryTests.CanFilter_FullNameEndsWith converts the following DTO expression:
```
.Call System.Linq.Queryable.Where(
.Call System.Linq.Queryable.OrderBy(
.Constant<System.Linq.EnumerableQuery`1[AutoMapperSamples.EF.Dtos.OrderDto]>(AutoMapperSamples.EF.Dtos.OrderDto[]),
'(.Lambda #Lambda1<System.Func`2[AutoMapperSamples.EF.Dtos.OrderDto,System.Double]>)),
'(.Lambda #Lambda2<System.Func`2[AutoMapperSamples.EF.Dtos.OrderDto,System.Boolean]>))
.Lambda …
```
> #2520 - Fixed Effort- and ODataQueryTests and a bug in ExpressionVisitor 

- src/AutoMapper/AssemblyInfo.cs
If you do not define the ComVisible Attribute .NET uses true as the default value and compiles the assembly as com visible. Fixes #2559.
> Define ComVisible Attribute

- src/AutoMapper/AdvancedConfiguration.cs
- src/AutoMapper/IConfigurationProvider.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/UnitTests/Projection/BindersAndResultConverters.cs
@TylerCarlson1's [idea](https://github.com/AutoMapper/AutoMapper/pull/2542#discussion_r171872523). It seems useful. Allow customizations to ProjectTo without affecting EF6. Also stuff like #2552 could be solved this way.
> ProjectTo : Expose binders and result converters

- README.md
I noticed the build status badge pointed to the build status of the develop branch. Not sure if this is intentional or not?
I've updated the link to point to the master branch.
> Update build status link

- docs/Mapping-inheritance.md
Updates unit test in text to match behavior as explained. Also adds a paragraph to make the explicit mapping using MapFrom more clear. This relates to issue #1100.
> Update unit test to match behavior as explained

- docs/Dependency-injection.md
AddProfiles recieves assembly types and not direct profiles .
Fixes DuplicateTypeMapConfigurationException in some cases
> Fixed documentation to not have   DuplicateTypeMap

- src/AutoMapper/AutoMapper.csproj
Adds information about the location of the repository to the project. This will end up in the .nuspec file automatically by msbuild.
Fixes #2631.
> Add repository information to csproj

- src/AutoMapper/Mappers/NullableDestinationMapper.cs
- src/UnitTests/Bug/NullableUntypedMapFrom.cs
The test is silly, but generic mapping works with expressions based on ```object```.
> Nullable untyped MapFrom

- src/AutoMapper/AutoMapper.csproj
- src/AutoMapper/Execution/PropertyDescription.cs
- src/AutoMapper/Execution/PropertyEmitter.cs
- src/AutoMapper/Execution/ProxyGenerator.cs
- src/AutoMapper/Execution/TypeDescription.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/LockingConcurrentDictionary.cs
- src/AutoMapper/Mapper.cs
- src/AutoMapper/Mappers/TypeConverterMapper.cs
- src/AutoMapper/PropertyMap.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/TypeExtensions.cs
- src/UnitTests/AutoMapper.UnitTests.csproj
- src/UnitTests/Bug/MapAtRuntimeWithCollections/EntityDTO20.cs
- src/UnitTests/DynamicMapping.cs
- src/UnitTests/InterfaceMapping.cs
- src/UnitTests/Internal/CreateProxyThreading.cs
- src/UnitTests/Projection/ProjectionTests.cs
Fixes #2680 
I had to target `netcoreapp2.0` directly. This will be an issue for folks using referencing AutoMapper transitively.
See https://github.com/dotnet/corefx/issues/29365
I think based on this we may want to consider removing any references to `System.Reflection.Emit`. This would mean losing support for mapping to interfaces, as well as the way we're doing `let` expressions for complex MapFrom's.
> Remove package references to System.Reflection.Emit

- docs/Conventions.md
Increase readability and don't break readthedocs page width (http://docs.automapper.org/en/stable/Conventions.html)
> Add code linebreaks

- src/AutoMapper/TypeExtensions.cs
- src/UnitTests/IgnoreAllPropertiesWithAnInaccessibleSetterTests.cs
Fix PropertiesWithAnInaccessibleSetter so that it also respects inherited properties, not only declared ones.
Fixes #2740.
> fix PropertiesWithAnInaccessibleSetter

- default.ps1
- docs/Dependency-injection.md
- docs/Value-converters.md
- docs/index.rst
- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/IMemberConfigurationExpression.cs
- src/AutoMapper/IValueConverter.cs
- src/AutoMapper/PropertyMap.cs
- src/AutoMapper/ValueConverterConfiguration.cs
- src/UnitTests/ValueConverters.cs
Fixes #2773 
This adds a new interface:
```c#
public interface IValueConverter<in TSourceMember, out TDestinationMember>
{
TDestinationMember Convert(TSourceMember sourceMember, ResolutionContext context);
}
```
Value converters are a cross between type converters and value resolvers. Because value converters are only scoped to members, this makes it much, much easier to reuse them across maps. These are the effective replacement for the old value formatters, minus the weird stacking of value formatters.
Unlike type converters, value converters are just another kind of value resolver, rather than something that completely overrides every other option. The precedence is:
- Value converter
- Value resolver
- Resolving func
- MapFrom expression
- Member matching
I thought this simplified …
> Value converters

- docs/8.0-Upgrade-Guide.md
- docs/index.rst
- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/IMappingExpression.cs
- src/IntegrationTests/BuiltInTypes/ProjectUsing.cs
- src/IntegrationTests/Inheritance/DerivedComplexTypes.cs
- src/UnitTests/ArraysAndLists.cs
- src/UnitTests/Bug/CannotProjectStringToNullableEnum.cs
- src/UnitTests/Bug/ProjectUsingTheQueriedEntity.cs
- src/UnitTests/CustomMapping.cs
- src/UnitTests/IMappingExpression/NonGenericProjectEnumTest.cs
- src/UnitTests/Projection/ProjectEnumTest.cs
- src/UnitTests/Projection/ProjectionTests.cs
> Consolidating ProjectUsing to ConvertUsing

- src/AutoMapper/PropertyMap.cs
- src/UnitTests/BidirectionalRelationshipsWithoutPR.cs
If you think the right fix is to introduce a complete interface implemented by both, I can do that. I wasn't convinced, so I didn't go that way.
> Set ignored in the property map constructed from a path map

- src/AutoMapper/AutoMapperMappingException.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/UnitTests/ForPath.cs
- src/UnitTests/MappingExceptions.cs
No longer restricted to property maps. Changes the exception object to include `IMemberMap` instead of just `PropertyMap`
> Contextual exceptions for path maps

- src/AutoMapper/ConfigurationValidator.cs
- src/AutoMapper/Mapper.cs
- src/AutoMapper/MapperConfiguration.cs
- src/AutoMapper/ProfileMap.cs
- src/AutoMapper/PropertyMap.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/Bug/UseDestinationValue.cs
- src/UnitTests/InterfaceMapping.cs
- src/UnitTests/OpenGenerics.cs
Fixes #2848. Closes #2843.
If the behavior is reasonable, I should probably add smth in the upgrade guide.
> Validate closed generic maps

- docs/Queryable-Extensions.md
- src/AutoMapper/IMapper.cs
- src/AutoMapper/Mapper.cs
- src/IntegrationTests/BuiltInTypes/ByteArray.cs
- src/IntegrationTests/BuiltInTypes/NullableToNonNullable.cs
- src/IntegrationTests/BuiltInTypes/ProjectEnumerableOfIntToList.cs
- src/IntegrationTests/BuiltInTypes/ProjectUsing.cs
- src/IntegrationTests/ChildClassTests.cs
- src/IntegrationTests/CustomMapFrom/CustomMapFromTest.cs
- src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
- src/IntegrationTests/ExplicitExpansion/ExpandCollections.cs
- src/IntegrationTests/ExplicitExpansion/ExpandCollectionsWithStrings.cs
- src/IntegrationTests/ExplicitExpansion/ExpandMembersPath.cs
- src/IntegrationTests/ExplicitExpansion/NestedExplicitExpand.cs
- src/IntegrationTests/ExplicitExpansion/NestedExplicitExpandWithFields.cs
- src/IntegrationTests/ExplicitExpansion/ProjectAndAllowNullCollections.cs
- src/IntegrationTests/ExplicitExpansion/ProjectionWithExplicitExpansion.cs
- src/IntegrationTests/ICollectionAggregateProjections.cs
- src/IntegrationTests/IEnumerableAggregateProjections.cs
- src/IntegrationTests/Inheritance/DerivedComplexTypes.cs
- src/IntegrationTests/Inheritance/ProjectToAbstractType.cs
- src/IntegrationTests/Inheritance/QueryableInterfaceInheritanceIssue.cs
- src/IntegrationTests/MaxDepth/MaxDepthWithCollections.cs
- src/IntegrationTests/MaxDepth/NavigationPropertySO.cs
- src/IntegrationTests/MaxDepth/NestedDtos.cs
- src/IntegrationTests/NullSubstitute.cs
- src/IntegrationTests/Parameterization/ParameterizedQueries.cs
- src/IntegrationTests/ProjectionOrder/ProjectionOrderTest.cs
- src/IntegrationTests/ValueTransformers/ValueTransformerTests.cs
- src/UnitTests/AutoMapperSpecBase.cs
Fixes #2857. I omitted the overloads with two parameters. I think we can live without them. People can easily add them, but I guess we could have them built in as extension methods.
> Added IMapper.ProjectTo

- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/IMappingExpression.cs
- src/UnitTests/BeforeAfterMapping.cs
This allows to use `ResolutionContext` when callbacks are added in `MapperConfigurationExpression.ForAllMaps()`, when only the non-templated `IMappingExpression` is available.
I guess the line encoding is buggy, so that's why the change is so big for `MappingExpression.cs`, but only lines 58-60 and 67-69 were added.
> Added methods BeforeMap and AfterMap for IMappingExpression with ResolutionContext

- src/AutoMapper/IMemberConfigurationExpression.cs
> We pass the destination member, not the source member

- src/AutoMapper/Configuration/IProfileConfiguration.cs
- src/AutoMapper/IProfileExpression.cs
- src/AutoMapper/Profile.cs
- src/AutoMapper/ProfileMap.cs
- src/AutoMapper/TypeDetails.cs
- src/UnitTests/ShouldMapMethod.cs
Add support to specify ShouldMapMethod to determine which methods, of those that are eligible to be mapped (parameterless, public, and non-static or extension methods) should be mapped.
Fixed #2959
> Add support to specify ShouldMapMethod 

- src/AutoMapper/MapperConfiguration.cs
- src/UnitTests/ConfigCompilation.cs
> Skip generic mappings when precompiling

- src/AutoMapper/AutoMapAttribute.cs
- src/UnitTests/AttributeBasedMaps.cs
Adding the following configuration options by the AutoMap attribute
- ConstructUsingServiceLocator
- MaxDepth
- PreserveReferences
- DisableCtorValidation
- IncludeAllDerived
- TypeConverter
#2936
> AutoMap attribute configuration options

- src/AutoMapper/Configuration/MapperConfigurationExpression.cs
- src/AutoMapper/ConstructorParameterMap.cs
- src/AutoMapper/DefaultMemberMap.cs
- src/AutoMapper/IMemberMap.cs
- src/AutoMapper/MemberFinderVisitor.cs
- src/AutoMapper/PathMap.cs
- src/AutoMapper/PropertyMap.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/Bug/MemberListSourceAndForPath.cs
Instead of only checking expression that have been created using `ForMember`, this also respects the `ForPath` configuration as well
Fixes #3000.
> Respect PathMappings in unmapped property names list

- src/AutoMapper/Mappers/EnumToEnumMapper.cs
- src/UnitTests/Bug/EnumCaseSensitivityBug.cs
Fixed enum value case insensitivity bug
Enum.GetName(sourceEnumType, source), true) the true here means parse case insensitive but the condition above was not case insensitive.
> fixed enum values caseinsensitivity bug

- src/AutoMapper/ProfileMap.cs
- src/UnitTests/MappingInheritance/IgnoreShouldBeInherited.cs
> Revert a recent change to Include

- src/AutoMapper/Execution/PropertyEmitter.cs
- src/AutoMapper/Execution/ProxyGenerator.cs
- src/AutoMapper/Mappers/FlagsEnumMapper.cs
- src/AutoMapper/ProfileMap.cs
To avoid unnecessary allocations.
> Type.EmptyTypes instead of new Type[0]

- src/AutoMapper/Mappers/MapperRegistry.cs
And adding a little code comment on the order of mappers so I don't forget how these are ordered and grouped.
> Moving enums after assignable to simplify assignable enums

- src/AutoMapper/ApiCompatBaseline.txt
- src/AutoMapper/Configuration/CtorParamConfigurationExpression.cs
- src/AutoMapper/Configuration/ICtorParameterConfiguration.cs
- src/AutoMapper/Configuration/MappingExpressionBase.cs
- src/AutoMapper/ProfileMap.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/TypeMapFactory.cs
- src/UnitTests/Constructors.cs
- src/UnitTests/Tests/TypeMapFactorySpecs.cs
> ForCtorParam MapFrom any expression

- docs/Conditional-mapping.md
Currently, the conditional mapping docs do not mention that a resolver will still run despite a Condition - this can be avoided with a PreCondition, but only if you knew that from reading the Custom Value Resolver docs.  There also is not a code example present using a PreCondition.
> Update Conditional Mapping docs

- src/AutoMapper/Internal/ExpressionFactory.cs
- src/UnitTests/CollectionMapping.cs
That's what the compiler does. I'm not sure anybody would write that, but here it is :)
> Don't check for IDisposable at runtime for value types

- src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs
- src/UnitTests/Projection/ProjectIReadOnlyCollection.cs
Fixes #3199. EF Core 3.0 supports `IReadOnlyCollection`.
> ProjectTo collections: Use IEnumerable if it's good enough and fallback to List

- src/AutoMapper/ProfileMap.cs
- src/UnitTests/Tests/TypeMapFactorySpecs.cs
Updated the ProfileMap.cs to add the MemberConfigurations from the global configuration to the profiles specified MemberConfigurations.
Fixes #3227.
> Fix inheritance of ReplaceMemberName global configuration in Profiles

- docs/Configuration.md
- docs/Dependency-injection.md
This small commit fixes the outdated API/documentation referencing AddProfiles(Assembly myAssembly) that doesn't exist.
> Fix outdated API/documentation (fixes #3260)

- src/AutoMapper/ConfigurationValidator.cs
- src/UnitTests/AdvancedConfiguration.cs
- src/UnitTests/ConfigurationValidation.cs
- src/UnitTests/CustomValidations.cs
If you use TypeConverters, this pull request allows you to add custom validators via Advanced.Validator
> Enabled custom validation for TypeConverters via Advanced.Validator

- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/ExpressionExtensions.cs
- src/UnitTests/IMappingExpression/IncludeMembers.cs
Fixes #3276 
I decided to go with replacing the expressions if they have a body that casts to object.
It's the strategy that has the smallest footprint on the source code.
> Add support for passing value-typed members to IncludeMembers

- docs/index.rst
I believe this should be a link, but was formatted incorrectly (it ends up as an italic)
> Fix .NET standard link on docs homepage

- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/Configuration/MemberConfigurationExpression.cs
- src/UnitTests/ReverseMapping.cs
- Added failing tests
Fixes #3329.
> Reverse the string based MapFrom

- src/AutoMapper/Configuration/MapperConfigurationExpression.cs
- src/UnitTests/AttributeBasedMaps.cs
Based on PR #3336
Added test and fix.
Fixes #3129 .
#3329
> Attribute-based reverse mapping with SourceMemberAttribute

- src/AutoMapper/Internal/MemberVisitor.cs
- src/IntegrationTests/ExplicitExpansion/ExpandCollections.cs
- src/IntegrationTests/ExplicitExpansion/ExplicitlyExpandCollectionsAndChildReferences.cs
> ProjectTo does not load expanded child collections.

- docs/Dependency-injection.md
I spent too much time figuring out how to register AutoMapper to the Catel.IoC services because I am new to DI. I've added an example for setting up DI for AutoMapper in Catel.IoC.
> Example for setting up DI for Catel.IoC

- src/AutoMapper/Execution/ExpressionBuilder.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/Mappers/Internal/CollectionMapperExpressionFactory.cs
- src/UnitTests/MaxDepthTests.cs
Breaking change. From #3391 and #2511. Another `if`, another dollar :) We can always keep the current behaviour.
> Avoid collections with null values when reaching max depth

- src/AutoMapper/ConstructorMap.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/UnitTests/Projection/ConstructorTests.cs
- src/UnitTests/Projection/MoreExplanatoryExceptionTests.cs
> EF Core; generalize constructor mapping for ProjectTo

- src/AutoMapper/Configuration/MappingExpression.cs
- src/AutoMapper/Configuration/MappingExpressionBase.cs
- src/AutoMapper/ConfigurationValidator.cs
- src/AutoMapper/DefaultMemberMap.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/ExpressionExtensions.cs
- src/AutoMapper/IMappingExpression.cs
- src/AutoMapper/IMemberMap.cs
- src/AutoMapper/Internal/ExpressionFactory.cs
- src/AutoMapper/Internal/MemberVisitor.cs
- src/AutoMapper/PathMap.cs
- src/AutoMapper/ProfileMap.cs
- src/AutoMapper/PropertyMap.cs
- src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
- src/AutoMapper/QueryableExtensions/ExpressionResolutionResult.cs
- src/AutoMapper/QueryableExtensions/Impl/CustomProjectionExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/MappedTypeExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/MemberGetterExpressionResultConverter.cs
- src/AutoMapper/QueryableExtensions/Impl/MemberResolverExpressionResultConverter.cs
- src/AutoMapper/QueryableExtensions/Impl/NullableDestinationExpressionBinder.cs
- src/AutoMapper/QueryableExtensions/Impl/QueryMapperHelper.cs
- src/AutoMapper/TypeMap.cs
- src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
- src/IntegrationTests/IncludeMembers.cs
- src/UnitTests/AutoMapperSpecBase.cs
- src/UnitTests/BasicFlattening.cs
- src/UnitTests/ForAllMembers.cs
- src/UnitTests/IMappingExpression/IncludeMembers.cs
- src/UnitTests/Internal/PrimitiveExtensionsTester.cs
The idea is to cache the included members. In a variable for `Map` and in a let clause for `ProjectTo`. I guess _any_ expression doesn't necessarily sound like a good idea. We'll see :)
> Allow any expression with IncludeMembers

- src/AutoMapper/Mappers/FromStringDictionaryMapper.cs
- src/UnitTests/Mappers/StringDictionaryMapperTests.cs
- Now when mapping from string dictionaries keys surrounded with white-spaces are considered
- Preferring the one with the least amount of white-spaces, when multiple entries are present
- Added matching tests
Fixes #3483
> Trim keys when mapping from dictionaries

- src/AutoMapper/Internal/TypeExtensions.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/ShouldUseConstructor.cs
This should fix calls to AssertConfigurationIsValid when using constructor mapping for classes with static constructors
Fixes #3476.
> Ignore static constructors

- src/AutoMapper/QueryableExtensions/Impl/AssignableExpressionBinder.cs
- src/UnitTests/Projection/ProjectionTests.cs
Hopefully we don't need to bring back the whole `NullableDestinationExpressionBinder`.
@jbogard If you're not releasing 10.1.1, I should probably move this to my branch.
> NonNullableToNullable

- src/AutoMapper/ProfileMap.cs
- src/UnitTests/MemberResolution.cs
According to [these lines](https://github.com/AutoMapper/AutoMapper/blob/6551613bcae9f391c50d392d94b5e5aad800a27f/src/AutoMapper/ProfileMap.cs#L54), `GlobalIgnores`, `SourceExtensionMethods`, `AllPropertyMapActions` and 
`AllTypeMapActions` of a profile are all concatenated with the global configuration.
`Prefixes` and `Postfixes` are not however, preventing the use of a global pre/postfixes definition.
```csharp
var configuration = new MapperConfiguration(config => {
// Only effective for maps created directly from config
config.RecognizePostfixes("Id");
config.AddProfile<SomeProfile>();
});
class SomeProfile : Profile
{
public SomeProfile ()
{
// One would have to uncomment this line for "Id" postfixes
// to be recognized while mapping from Source to Destination …
```
> Global pre and postfixes

- src/AutoMapper/AutoMapperMappingException.cs
HI @jbogard!
In some null-check conditions, the null-conditional operator is not needed.
`Types` is a Nullable type and we can use the `HasValue` and `Value` function for null-checking.
> Remove not needed null-conditional operators

- src/AutoMapper/Mappers/ConversionOperatorMapper.cs
- src/UnitTests/Mappers/ConversionOperators.cs
This PR adds support for inherited operators conversion from the source type. Conversion operators on the destination type do not apply here (the operator needs to be about the enclosing type).
I used a modified value of [TypeExtensions.StaticFlags](https://github.com/AutoMapper/AutoMapper/blob/bdc0120497d192a2741183415543f6119f50a982/src/AutoMapper/Internal/TypeExtensions.cs#L12) in the same idea as [this line](https://github.com/AutoMapper/AutoMapper/blob/bdc0120497d192a2741183415543f6119f50a982/src/AutoMapper/Internal/TypeExtensions.cs#L16) to match already existing code.
For instance with these changes, such use case works out of the box.
```csharp
public class IntValue
{
public IntValue(int value)
{
Value = value;
}
public int Value { get; }
public static explicit operator …
```
> Inherited source operators support for ConversionOperatorMapper

- docs/Flattening.md
- src/AutoMapper/Configuration/ConfigurationValidator.cs
- src/AutoMapper/Configuration/MapperConfiguration.cs
- src/AutoMapper/Internal/TypeExtensions.cs
- src/AutoMapper/Mappers/CollectionMapper.cs
- src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs
- src/UnitTests/CollectionMapping.cs
For better or worse, this favours backward compatibility without giving up the performance gains.
> Assign collections we can't handle 

- src/AutoMapper/AutoMapper.csproj
- src/AutoMapper/PreBuild.sh
- src/UnitTests/Internationalization.cs
- src/UnitTests/Tests/TypeMapFactorySpecs.cs
I wanted to test the next major of MinVer on a few repos which consume it, but I was stuck with AutoMapper because it currently only build on Windows.
> allow building on Linux (and probably macOS)

- src/AutoMapper/ApiCompatBaseline.txt
- src/AutoMapper/Configuration/IMappingExpressionBase.cs
- src/AutoMapper/Configuration/MappingExpressionBase.cs
- src/UnitTests/InterfaceMapping.cs
https://github.com/AutoMapper/AutoMapper/discussions/3889
> Continue chaining after AsProxy

- src/AutoMapper/Internal/TypeDetails.cs
GetPublicNoArgExtensionMethods tries to instantiate arbitrary generic methods with arbitrary type arguments, which can fail if those arguments don't meet any constraints defined on the generic parameters. Automapper isn't doing the required checking for constraint validation today, resulting in exceptions escaping; multiple existing Automapper unit tests fail on .NET 7 as a result.  This works around it by eating the ArgumentException that comes from MakeGenericMethod (there's no exposed compatibility-checking function, and so while not usually recommended, the most reliable thing here is to simply catch the errors stemming from the validation MakeGenericMethod performs).
Fixes https://github.com/AutoMapper/AutoMapper/issues/3988
> Suppress generic constraint exceptions in GetPublicNoArgExtensionMethods

- src/AutoMapper/Execution/ExpressionBuilder.cs
- src/AutoMapper/Execution/TypeMapPlanBuilder.cs
- src/AutoMapper/TypeMap.cs
- src/UnitTests/NullBehavior.cs
> Null source member should overwrite existing destination member

- src/IntegrationTests/Inheritance/ProjectToAbstractTypeWithInheritance.cs
Add an integration test case reproducing the issue with polymorphic element projection.
> Add integration test case

- src/AutoMapper/AutoMapper.csproj
Microsoft.CSharp alreary included in .NET Core and no need to add it as nuget pacakge
> Remove Microsoft.CSharp nuget dependency

- src/AutoMapper/Configuration/MapperConfigurationExpression.cs
- src/AutoMapper/Mapper.cs
- src/AutoMapper/QueryableExtensions/Extensions.cs
This reverts commit 7bd1b81cde5667458739bb9b50889589f07ecae5.
> Revert "nullable annotations for the runtime public API"

- .github/workflows/ci.yml
- .github/workflows/lock.yml
- .github/workflows/release.yml
- src/AutoMapper.DI.Tests/AutoMapper.DI.Tests.csproj
- src/AutoMapper/ApiCompat/PreBuild.ps1
- src/AutoMapper/AutoMapper.csproj
- src/AutoMapper/Internal/ReflectionHelper.cs
- src/Benchmark/Benchmark.csproj
- src/IntegrationTests/AutoMapper.IntegrationTests.csproj
- src/TestApp/TestApp.csproj
- src/UnitTests/AutoMapper.UnitTests.csproj
> Target .Net 9 in tests

- src/AutoMapper/AutoMapper.csproj
no longer required since SDK 8
https://github.com/dotnet/sourcelink?tab=readme-ov-file#using-source-link-in-net-projects
> remove Microsoft.SourceLink.GitHub

- .github/workflows/ci.yml
- src/AutoMapper/AutoMapper.csproj
- src/IntegrationTests/AutoMapper.IntegrationTests.csproj
- src/UnitTests/AutoMapper.UnitTests.csproj
> Direct .NET 4.x support
