src/AutoMapper/ConfigurationStore.cs
Used your feedback as a basis for this.
=> Fix for #724

src/AutoMapper/Internal/ReflectionHelper.cs, src/AutoMapper/QueryableExtensions/ProjectionExpression.cs, src/IntegrationTests.Net4/ExpandCollections.cs, src/IntegrationTests.Net4/ExpandCollectionsWithStrings.cs, src/IntegrationTests.Net4/IntegrationTests.Net4.csproj, src/IntegrationTests.Net4/ProxyTests.cs
=> Support expand with collections

src/AutoMapper/Internal/ReflectionHelper.cs, src/AutoMapper/QueryableExtensions/ProjectionExpression.cs, src/IntegrationTests.Net4/ExpandMembersPath.cs, src/IntegrationTests.Net4/IntegrationTests.Net4.csproj
=> Expand everything on the path to the passed member

src/AutoMapper/ConfigurationStore.cs, src/AutoMapper/Internal/MappingExpression.cs, src/AutoMapper/TypeMap.cs, src/UnitTests/Bug/IncludeBaseInheritance.cs, src/UnitTests/Bug/IncludeInheritance.cs, src/UnitTests/UnitTests.Net4.csproj
=> Include base inheritance bug 911

src/AutoMapper/AutoMapperMappingException.cs, src/AutoMapper/ResolutionContext.cs, src/UnitTests/Bug/ExceptionDestinationPath.cs, src/UnitTests/UnitTests.Net4.csproj
Reported in #892. But this is just the symptom.
=> Fixed duplicated path in the exception message

src/AutoMapper/TypeMapFactory.cs, src/UnitTests/Constructors.cs
=> We can resolve optional parameters

src/AutoMapper/Mapper.cs, src/AutoMapper/QueryableExtensions/Extensions.cs, src/UnitTests/Projection/ParameterizedQueriesTests.cs
=> Adding legacy LINQ methods

src/AutoMapper/ConfigurationValidator.cs, src/AutoMapper/MapperConfiguration.cs
MapperConfiguration was geting a little unwieldy with the validation in there
=> Broke out configuration validation from the mapper configuration

src/AutoMapper/MapperConfiguration.cs, src/UnitTests/Bug/ReportMissingInclude.cs
=> Fixes #1077

src/AutoMapper/Mapper.cs, src/AutoMapper/QueryableExtensions/Extensions.cs, src/UnitTests/StaticMapping.cs, src/UnitTests/UnitTests.Net4.csproj
=> Restores Mapper.Initialize and Mapper.Map

src/AutoMapper/Execution/PropertyAccessor.cs, src/AutoMapper/Mappers/TypeMapObjectMapperRegistry.cs, src/AutoMapper/PropertyMap.cs
Get Rid of HasSetter and it's wasteful wasteful type and property checking.
Not much performance gain, but some
=> No More HasSetter

src/AutoMapper.Net4/AutoMapper.Net4.csproj, src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Configuration/MemberConfigurationExpression.cs, src/AutoMapper/Execution/DelegateBasedResolver.cs, src/AutoMapper/Execution/DelegateFactory.cs, src/AutoMapper/Execution/FieldAccessor.cs, src/AutoMapper/Execution/FieldGetter.cs, src/AutoMapper/Execution/IDelegateFactory.cs, src/AutoMapper/Execution/MemberGetter.cs, src/AutoMapper/Execution/MethodGetter.cs, src/AutoMapper/Execution/NullReferenceExceptionSwallowingResolver.cs, src/AutoMapper/Execution/PropertyAccessor.cs, src/AutoMapper/Execution/PropertyGetter.cs, src/AutoMapper/Execution/ReflectionHelper.cs, src/AutoMapper/Execution/ValueTypeFieldAccessor.cs, src/AutoMapper/Execution/ValueTypePropertyAccessor.cs, src/AutoMapper/IMemberAccessor.cs, src/AutoMapper/IMemberGetter.cs, src/AutoMapper/IMemberResolver.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/Mappers/EnumMapper.cs, src/AutoMapper/PropertyMap.cs, src/UnitTests/ExtensionMethods.cs, src/UnitTests/Internal/DelegateFactoryTests.cs, src/UnitTests/NullBehavior.cs, src/UnitTests/ValueTypes.cs
Still have 3 failing tests, 2 of which have to do with open generics types.
Still can optimize more with a complete set action, but for now it can get and set.
=> [WIP] Remove type map registry

src/AutoMapper/TypeMap.cs
[Before](https://cloud.githubusercontent.com/assets/4517428/13574629/9f54a13e-e48d-11e5-91a2-eed251c985bd.png) & [after](https://cloud.githubusercontent.com/assets/4517428/13574628/9f547fba-e48d-11e5-9b55-4b0e11841eb4.png).
=> Useless allocations - Action after/before map

src/AutoMapper/MappingOperationOptions.cs
[Before](https://cloud.githubusercontent.com/assets/4517428/13573722/b43d7f20-e489-11e5-80ad-20b4d8072444.png) & [after](https://cloud.githubusercontent.com/assets/4517428/13573723/b43dcd9a-e489-11e5-8fed-9ab5a0ce1fbd.png).
=> Useless allocations - MappingOperationOptions

src/AutoMapper/ConstructorMap.cs, src/AutoMapper/MappingEngine.cs, src/AutoMapper/TypeMap.cs, src/AutoMapper/TypeMapFactory.cs
[Before](https://cloud.githubusercontent.com/assets/4517428/13571384/3cac2738-e47d-11e5-8295-5a3e29351bc3.png) & [after](https://cloud.githubusercontent.com/assets/4517428/13571383/3cac0c8a-e47d-11e5-860d-7a23470c4cea.png).
=> Useless allocations - Enumerators

src/AutoMapper/MapperConfiguration.cs
[Before](https://cloud.githubusercontent.com/assets/4517428/13569360/4ce702a6-e470-11e5-9b1f-c151b4dec4b9.png) & [after](https://cloud.githubusercontent.com/assets/4517428/13569359/4ce56626-e470-11e5-87d0-2be813475e94.png).
=> Useless allocations - Funcs

src/AutoMapper/Mapper.cs, src/Benchmark/Program.cs
[Before](https://cloud.githubusercontent.com/assets/4517428/13604011/6af8488e-e549-11e5-9cb5-832e90054dc6.png) & [after](https://cloud.githubusercontent.com/assets/4517428/13604010/6ae01ac0-e549-11e5-89e1-a6d02fc34b5e.png).
=> Allocate MappingOperationOptions only when needed

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/IMappingExpression.cs, src/AutoMapper/IMappingOperationOptions.cs, src/AutoMapper/MappingEngine.cs, src/AutoMapper/MappingOperationOptions.cs, src/AutoMapper/ResolutionContext.cs, src/AutoMapper/TypeMap.cs, src/UnitTests/BidirectionalRelationships.cs, src/UnitTests/Bug/DuplicateValuesBug.cs, src/UnitTests/MaxDepthTests.cs
=> Disable the cache by default

src/AutoMapper/Execution/DelegateFactory.cs
[Before](https://cloud.githubusercontent.com/assets/4517428/13641190/32f3bb08-e620-11e5-8cb1-d11bd3ab804c.png) & [after](https://cloud.githubusercontent.com/assets/4517428/13641189/3293a3ee-e620-11e5-8d0c-36b1eb5fb07a.png).
=> Unnecessary Func allocations in DelegateFactory

src/AutoMapper/ConstructorMap.cs, src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/Mapper.cs, src/AutoMapper/TypeMap.cs
[Before](https://cloud.githubusercontent.com/assets/4517428/13640021/ec66519a-e61b-11e5-9053-c230f928715d.png) & [after](https://cloud.githubusercontent.com/assets/4517428/13640020/ec65c77a-e61b-11e5-94c8-800126b65e0a.png).
=> Unnecessary enumerator allocations

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Configuration/PrimitiveExtensions.cs, src/IntegrationTests.Net4/IntegrationTests.Net4.csproj, src/IntegrationTests.Net4/QueryableInterfaceInheritanceIssue.cs, src/UnitTests/InterfaceMapping.cs
The diff is messed up for PrimitiveExtensions.cs. I just added code, probably a whitespace thing. #1181 seems to work on develop.
=> Base interface members

src/AutoMapper/Profile.cs, src/UnitTests/MappingInheritance/ApplyIncludeBaseRecursively.cs, src/UnitTests/MappingInheritance/IncludeBaseShouldNotCreateMaps.cs, src/UnitTests/UnitTests.Net4.csproj
=> Include recursively all the base maps

src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/ICtorParamConfigurationExpression.cs, src/UnitTests/IMappingExpression/ForCtorParam.cs
See #1209 for a use case.
Not sure I did this the right way, so feedback is very welcome, but there's at least a test that shows the new API and it works the way I'd expect it :)
=> Implement ResolveUsing for constructor parameters

src/AutoMapper/ConstructorMap.cs, src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/PropertyMap.cs, src/AutoMapper/TypeMap.cs, src/AutoMapper/TypeMapFactory.cs
=> Ctors based on expressions

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/IProfileConfiguration.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/Profile.cs, src/AutoMapper/TypeExtensions.cs, src/AutoMapper/TypePair.cs, src/UnitTests/Bug/GenericTypeConverter.cs, src/UnitTests/Should/Should.Core/Assertions/AssertComparer.cs
=> Implemented mapping between open generic and nongeneric or closed generic types

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/ConstructorMap.cs, src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/Execution/DelegateFactory.cs, src/AutoMapper/Mapper.cs, src/AutoMapper/PropertyMap.cs, src/AutoMapper/TypeExtensions.cs, src/AutoMapper/TypeMap.cs, src/Benchmark/FlatteningMapper.cs, src/Benchmark/IObjectToObjectMapper.cs, src/Benchmark/Program.cs, src/UnitTests/BasicFlattening.cs, src/UnitTests/UnitTests.Net4.csproj
=> Expression optimization

src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/TypeExtensions.cs, src/UnitTests/Bug/GenericTypeConverter.cs
Two issues uncovered in #1112 that predate my first PR.
=> Fixes for issues in #1112

src/AutoMapper/PropertyMap.cs, src/UnitTests/Bug/ForAllMembersAndDoNotUseDestinationValue.cs, src/UnitTests/UnitTests.Net4.csproj
https://github.com/AutoMapper/AutoMapper/issues/726#issuecomment-211529672
=> DoNotUseDestinationValue should work for value types too

src/AutoMapper/TypeMap.cs, src/UnitTests/MappingOrder.cs
https://github.com/AutoMapper/AutoMapper/issues/339#issuecomment-209358649
=> Inherit the mapping order

src/AutoMapper/ConstructorMap.cs, src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs, src/AutoMapper/QueryableExtensions/Impl/MemberGetterExpressionResultConverter.cs, src/UnitTests/Projection/MapFromTest.cs
I hope I'm not missing smth. This is simple stuff.
=> MapFrom should override matching source member

src/AutoMapper/Profile.cs, src/AutoMapper/TypeExtensions.cs, src/UnitTests/Bug/GenericTypeConverter.cs
https://github.com/AutoMapper/AutoMapper/issues/774#issuecomment-213489884
=> Generic type converter with two type parameters

src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/Execution/DelegateFactory.cs, src/AutoMapper/Execution/ReflectionHelper.cs, src/UnitTests/Constructors.cs
http://stackoverflow.com/questions/36173391/getting-defaultvalue-for-optional-guid-through-reflection
=> Default value for Guid; fixes #1254

src/AutoMapper/Mapper.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/Mappers/EnumerableMapperBase.cs, src/UnitTests/Bug/CollectionWhere.cs, src/UnitTests/Bug/MapOverloadsWithDynamic.cs, src/UnitTests/General.cs, src/UnitTests/UnitTests.Net4.csproj
consider existing destinations when creating objects
fixes #1257
=> Always generate typed mapping funcs

src/AutoMapper/Configuration/Conventions/PrePostfixName.cs, src/UnitTests/MemberResolution.cs
=> Pre and post fixes now case insensitive

src/AutoMapper/IConfigurationProvider.cs, src/AutoMapper/Mapper.cs, src/AutoMapper/MapperConfiguration.cs
I couldn't get dynamic to work. This seems to do the job.
=> Use casting instead of DynamicInvoke

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/CustomMapping.cs
Sorry for the whitespace thing. I did it in a separate commit but I guess that's not enough.
=> Resolve using with different types

src/AutoMapper/ConstructorMap.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs
Simplifies the constructor map expression.
=> Share the context between property mapping and constructor mapping

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/TypeMap.cs, src/UnitTests/Constructors.cs
I just added one test at the top, github can't handle the truth (whitespace) :)
=> Don't map through properties members mapped through the constructor

src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/Execution/ReflectionHelper.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/Mappers/ArrayMapper.cs, src/AutoMapper/Mappers/CollectionMapper.cs, src/AutoMapper/Mappers/DictionaryMapper.cs, src/AutoMapper/Mappers/DynamicMappers.cs, src/AutoMapper/Mappers/EnumerableMapper.cs, src/AutoMapper/Mappers/EnumerableToDictionaryMapper.cs, src/AutoMapper/Mappers/HashSetMapper.cs, src/AutoMapper/Mappers/ReadOnlyCollectionMapper.cs, src/AutoMapper/Mappers/StringDictionaryMapper.cs, src/AutoMapper/ResolutionContext.cs, src/Benchmark/Benchmark.csproj
Got About 15-20% performance boost from Complex Types from Mapster test in #1329
=> Remove Unneeded casting from ResolutionContext.Map

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/TypeExtensions.cs, src/UnitTests/ConditionalMapping.cs, src/UnitTests/Internal/PrimitiveExtensionsTester.cs
Whitespace in ConditionalMapping.cs. The test is at the top.
=> Ignore explicit interface implementations with no setter

src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/ExpressionExtensions.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/Mappers/ArrayMapper.cs, src/AutoMapper/Mappers/CollectionMapper.cs
This one was big, the collection/complex ones dropped the times nearly in half locally.
=> Inline the lambdas as necessary

src/AutoMapper/Execution/DelegateFactory.cs, src/UnitTests/Bug/UseDestinationValue.cs, src/UnitTests/Internal/DelegateFactoryTests.cs, src/UnitTests/UnitTests.Net4.csproj
=> Fixes #1350

src/AutoMapper/project.json
=> Fix buildOptions

src/AutoMapper/MapperConfiguration.cs, src/UnitTests/Bug/MissingMapping.cs, src/UnitTests/UnitTests.Net4.csproj
=> Specify the type of the parameter for missing map exception

src/AutoMapper/Mapper.cs, src/AutoMapper/TypePair.cs
The nullable check is not required anymore or we need more tests :)
=> Remove the nullable check and avoid boxing

src/UnitTests/Bug/CustomConverters.cs
=> Closes #1389

src/AutoMapper/ExpressionExtensions.cs
the static visitor is a memory leak
replace the list with a HashSet, just in case there are many nodes
=> IfNullVisitor memory leak

src/AutoMapper/ConfigurationValidator.cs, src/UnitTests/ConfigurationValidation.cs
Whitespace in UnitTests/ConfigurationValidation.cs. The tests are at the top. I was not sure if there are other similar cases.
=> Fixes #1380

src/AutoMapper/Execution/TypeMapPlanBuilder.cs
=> Make Condition like pre-condition with IfThen

src/AutoMapper/Mappers/CollectionMapper.cs, src/UnitTests/ArraysAndLists.cs
=> Don't modify the method argument; fixes #1424

src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs, src/IntegrationTests.Net4/ByteArray.cs, src/IntegrationTests.Net4/IntegrationTests.Net4.csproj
=> ProjectTo with byte array

src/AutoMapper/Configuration/PrimitiveExtensions.cs, src/AutoMapper/Mappers/DictionaryMapper.cs, src/UnitTests/Bug/MapExpandoObjectProperty.cs, src/UnitTests/UnitTests.Net4.csproj
Was counting ExpandoObject as dictionary type and using it as DictionaryMapper
Fixes #1418
=> Expando object bug

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/IMappingExpression.cs, src/AutoMapper/ITypeConverter.cs, src/AutoMapperSamples/GlobalTypeConverters.cs, src/UnitTests/BidirectionalRelationships.cs, src/UnitTests/Bug/CustomConverters.cs, src/UnitTests/Bug/CustomIEnumerableBug.cs, src/UnitTests/Bug/GenericTypeConverter.cs, src/UnitTests/Bug/MultipleTypeConverterInterfaces.cs, src/UnitTests/Bug/NullableConverterBug.cs, src/UnitTests/ConfigurationValidation.cs, src/UnitTests/CustomMapping.cs, src/UnitTests/ExpressionBridge.cs, src/UnitTests/NestedContainers.cs, src/UnitTests/NullBehavior.cs, src/UnitTests/TypeConverters.cs
=> Restoring destination value in type converters

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/Mappers/CollectionMapper.cs, src/AutoMapper/TypeMap.cs, src/AutoMapper/project.json, src/UnitTests/Bug/ConventionCreateMapsWithCircularReference.cs, src/UnitTests/UnitTests.Net4.csproj
=> Create missing map circular reference

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/ExpressionExtensions.cs, src/AutoMapper/Mappers/CollectionMapper.cs, src/AutoMapper/Mappers/ExplicitConversionOperatorMapper.cs, src/AutoMapper/Mappers/ImplicitConversionOperatorMapper.cs, src/AutoMapper/Mappers/StringMapper.cs, src/AutoMapper/TypeExtensions.cs, src/UnitTests/Bug/InitializeNRE.cs, src/UnitTests/UnitTests.Net4.csproj
renamed methods to execute the same code on .NET Core and .NET 4.5
=> Fixes #1453

src/AutoMapper/AutoMapperConfigurationException.cs, src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/ConfigurationValidator.cs, src/AutoMapper/IMappingExpression.cs, src/AutoMapper/TypeMap.cs, src/UnitTests/ConfigurationValidation.cs
=> Validating constructor mapping as part of configuration validation

src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs, src/IntegrationTests.Net4/IntegrationTests.Net4.csproj, src/IntegrationTests.Net4/ProjectUsing.cs
=> Better match condition for enumerables

src/AutoMapper/TypeMap.cs, src/UnitTests/Bug/SamePropertyNameOnParentAndChildClasses.cs, src/UnitTests/UnitTests.Net4.csproj
Check member info if it's the same type as TypeMap before checking names.
=> Fixes #1497

src/AutoMapper/Configuration/Conventions/AllMemberInfo.cs, src/AutoMapper/Configuration/Conventions/NameSplitMember.cs, src/AutoMapper/Configuration/Conventions/PrePostfixName.cs, src/AutoMapper/Configuration/PrimitiveExtensions.cs, src/AutoMapper/IProfileConfiguration.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/Mappers/ConvertMapper.cs, src/AutoMapper/Mappers/DynamicMappers.cs, src/AutoMapper/Mappers/StringDictionaryMapper.cs, src/AutoMapper/Profile.cs, src/AutoMapper/TypeDetails.cs, src/AutoMapper/TypeMapFactory.cs, src/UnitTests/UnitTests.Net4.csproj
Made configuration faster, about 2-3x in a local project. @TylerCarlson1 I poked a bit around the convention stuff to precalculate some stuff that was getting calculated every time.
=> Configuration faster

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/TypeMap.cs, src/UnitTests/Constructors.cs
More readable code in my view.
=> Refactor from statics and parameters to instance methods and fields

src/AutoMapper/ConstructorMap.cs, src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/Mappers/ArrayMapper.cs, src/AutoMapper/Mappers/CollectionMapper.cs, src/AutoMapper/TypeMap.cs, src/UnitTests/TypeConverters.cs
fixes #1529
use ResolveTypeMap instead of GetTypeMap
special case CreateMissingTypeMaps to avoid the overhead on the normal path
=> Convert using to string

src/AutoMapper/Configuration/MemberConfigurationExpression.cs, src/AutoMapper/IMemberConfigurationExpression.cs, src/AutoMapper/PropertyMap.cs, src/AutoMapper/QueryableExtensions/Impl/MappedTypeExpressionBinder.cs
@jbogard anything I missed? (didn't have time to test)
=> Add an AllowNull configuration

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/Mappers/CollectionMapper.cs
This is supposed to be a refactoring for the generated code.
=> Generate more readable code

src/AutoMapper/Configuration/MemberConfigurationExpression.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/IMemberConfigurationExpression.cs, src/UnitTests/Bug/NullSubstituteInnerClass.cs, src/UnitTests/UnitTests.Net4.csproj
=> The null substitute should have the same type as the value resolved

src/UnitTests/Constructors.cs
=> Constructor tests with prefixes and postfixes for source and destination

src/AutoMapper/ConstructorMap.cs, src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/Mappers/CollectionMapper.cs, src/UnitTests/Constructors.cs
=> Resolve and then map if needed

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/CollectionMapping.cs
Fixes #1581. Make a new local to avoid the error.
=> Struct with collection

src/AutoMapper/Execution/DelegateFactory.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/TypeMap.cs, src/UnitTests/NullBehavior.cs
=> Map from null interface

src/AutoMapper/Mappers/CollectionMapper.cs, src/UnitTests/CollectionMapping.cs
=> Just clear the destination everytime we don't create it ourselves

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/TypePair.cs, src/UnitTests/TypeConverters.cs
I believe my initial fix for a similar problem was a global fix for a local issue so I reverted it. Again the root problem is changing the type of the expression. I guess this applies everywhere IfNotNull is called, but I thought the problem is subtle enough to wait.
=> Decimal to nullable decimal

src/AutoMapper/ExpressionExtensions.cs, src/UnitTests/BasicFlattening.cs
=> Short-circuit evaluation

src/AutoMapper/Mappers/CollectionMapper.cs, src/UnitTests/CollectionMapping.cs
=> Get the element type from the destination object itself

src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
https://github.com/AutoMapper/AutoMapper/pull/1649#issuecomment-242667629
=> Not needed code - null substitute

src/AutoMapper/MapperConfiguration.cs
While testing nullable stuff I saw this code. Maybe it just needs a test.
=> Not needed code - nullables

src/AutoMapper/MappingOperationOptions.cs, src/UnitTests/TypeConverters.cs
=> Make it easier to spot missing services

src/AutoMapper/Configuration/PrimitiveExtensions.cs, src/AutoMapper/ExpressionExtensions.cs, src/AutoMapper/Mappers/ArrayMapper.cs, src/AutoMapper/Mappers/CollectionMapper.cs, src/AutoMapper/Mappers/TypeHelper.cs, src/UnitTests/Bug/JsonNet.cs
=> Multiple IEnumerable interfaces

src/AutoMapper/Profile.cs, src/UnitTests/DynamicMapping.cs
=> Mapping to/from object doesn't seem useful

src/AutoMapper/Mappers/EnumMapper.cs, src/UnitTests/Enumerations.cs
=> Map string to nullable enum

src/AutoMapper/Mappers/ExpressionMapper.cs, src/UnitTests/Bug/ExpressionMapping.cs
=> Checking for closures (constant expressions) when mapping expressions

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/CustomMapping.cs
So I put the bug in there by checking for value types, because of some weird expressions error complaining about value types. Now, presumably because of some generated code refactorings, everything works like a charm :)
=> Catch NRE in MapFrom with value types; fixes #1798

src/AutoMapper/Mappers/ConvertMapper.cs, src/UnitTests/Mappers/ConvertMapperTests.cs
=> Return null when mapping from null string to nullable

src/AutoMapper/Configuration/MapperConfigurationExpression.cs
=> Filtering dynamic assemblies

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/IMappingExpression/NonGenericResolveUsing.cs, src/UnitTests/UnitTests.Net4.csproj
From https://github.com/AutoMapper/AutoMapper/issues/1795#issuecomment-262282103.
=> Add required casts for non generic ResolveUsing

src/UnitTests/Bug/CollectionsNullability.cs, src/UnitTests/Bug/ConstructUsingReturnsNull.cs, src/UnitTests/Projection/ProjectCollectionEnumerableTest.cs, src/UnitTests/Projection/ProjectCollectionListTest.cs, src/UnitTests/Projection/ProjectTest.cs
The ProjectTo tests without the DB can be misleading.
=> Make a decision about the skipped tests.

src/AutoMapper/MapperConfiguration.cs, src/UnitTests/BuildExecutionPlan.cs, src/UnitTests/UnitTests.Net4.csproj
=> Expose the execution plan

src/AutoMapper/MapperConfiguration.cs
Closes #1842. I've also linked to it from the home page, the section General Features. Any better idea? :)
=> Add a link to the wiki

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/BasicFlattening.cs
=> Always null check

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Configuration/MemberConfigurationExpression.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/ValueResolverConfiguration.cs, src/UnitTests/CustomMapping.cs
Fixes #1887.
Of course we _don't have to_ support that scenario :)
=> Multiple value resolver interfaces

src/AutoMapper/Mappers/ExpressionMapper.cs, src/UnitTests/Bug/ExpressionMappingPropertyFromBaseClass.cs, src/UnitTests/Query/SourceInjectedQuery.cs, src/UnitTests/UnitTests.Net4.csproj
I implemented fix as TylerCarlson1 proposed and added unit test
=> fix for issue 1886 and unit test in SourceInjectedQuery class

src/AutoMapper/TypePair.cs
=> Code that was left behind when TypePair was made a struct

src/AutoMapper/AutoMapperConfigurationException.cs, src/AutoMapper/ConfigurationValidator.cs, src/AutoMapper/Mappers/CollectionMapper.cs, src/AutoMapper/Mappers/EnumerableMapper.cs, src/UnitTests/CollectionMapping.cs
Fixes #1905.
I've also fixed an issue with validation, the property in error was not reported.
Fixes #1908.
=> Support older collection types

src/AutoMapper/AdvancedConfiguration.cs, src/AutoMapper/ConfigurationValidator.cs, src/AutoMapper/IConfigurationProvider.cs, src/AutoMapper/MapperConfiguration.cs, src/UnitTests/ConfigurationValidation.cs
For things like #1907 and #1609.
=> Custom config validation

src/AutoMapper/QueryableExtensions/ProjectionExpression.cs, src/UnitTests/Projection/MembersToExpand_ExpressionArray.cs, src/UnitTests/UnitTests.Net4.csproj
=> 5.2.0 issue value type projection expression

src/AutoMapper/ExpressionExtensions.cs, src/AutoMapper/Mappers/EnumToUnderlyingTypeMapper.cs, src/AutoMapper/Mappers/FlagsEnumMapper.cs, src/AutoMapper/Mappers/NameValueCollectionMapper.cs, src/AutoMapper/Mappers/ToDynamicMapper.cs, src/AutoMapper/Mappers/UnderlyingTypeToEnumMapper.cs
=> Inline map calls to expressions

src/AutoMapper/MapperConfiguration.cs, src/UnitTests/Bug/MultiThreadingIssues.cs
This is what I meant. But a test is the best :)
=> We need the lock

src/AutoMapper/Mappers/FromDynamicMapper.cs, src/AutoMapper/Mappers/ToDynamicMapper.cs, src/UnitTests/Mappers/DynamicMapperTests.cs
=> Passing the type doesn't seem to help

src/AutoMapper/Execution/DelegateFactory.cs, src/UnitTests/Mappers/StringDictionaryMapperTests.cs
=> Consider abstract types

src/AutoMapper/Mappers/Internal/CollectionMapperExpressionFactory.cs, src/UnitTests/CollectionMapping.cs
=> Allow source struct collections

src/AutoMapper/Mappers/EnumerableMapper.cs, src/UnitTests/CollectionMapping.cs
=> Use the existing destination

src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs, src/AutoMapper/QueryableExtensions/Impl/NullableDestinationExpressionBinder.cs, src/AutoMapper/QueryableExtensions/Impl/NullableSourceExpressionBinder.cs, src/IntegrationTests.Net4/IntegrationTests.Net4.csproj, src/IntegrationTests.Net4/NullableLongToLong.cs, src/IntegrationTests.Net4/NullableToNonNullable.cs
Fixes #2082. Unless some other code should have handled it...
The IsMatch condition is fuzzy, but IsAssignableFrom doesn't help and I don't have a better idea.
=> Project nullable to GetValueOrDefault

src/AutoMapper/ConfigurationValidator.cs, src/UnitTests/Bug/NullableToInvalid.cs, src/UnitTests/UnitTests.Net4.csproj
=> Check the underlying type

src/AutoMapper/Configuration/IPropertyMapConfiguration.cs, src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Configuration/MemberConfigurationExpression.cs, src/AutoMapper/Configuration/MemberPath.cs, src/AutoMapper/Configuration/PathConfigurationExpression.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/ExpressionExtensions.cs, src/AutoMapper/IMappingExpression.cs, src/AutoMapper/IPathConfigurationExpression.cs, src/AutoMapper/Internal/MemberVisitor.cs, src/AutoMapper/ProfileMap.cs, src/AutoMapper/PropertyMap.cs, src/UnitTests/ReverseMapping.cs
=> Reverse MapFrom

src/AutoMapper/TypeMapFactory.cs, src/UnitTests/Constructors.cs
=> Consider only constructors that can resolve all parameters

src/AutoMapper/ConfigurationValidator.cs, src/AutoMapper/IObjectMapperInfo.cs, src/AutoMapper/Mappers/ArrayMapper.cs, src/AutoMapper/Mappers/CollectionMapper.cs, src/AutoMapper/Mappers/EnumerableMapper.cs, src/AutoMapper/Mappers/EnumerableMapperBase.cs, src/AutoMapper/Mappers/NullableSourceMapper.cs
Fixes #2101.
@jbogard I don't know if this is what you had in mind, but I think it does the job.
=> Make object mappers help with validation

src/AutoMapper/Configuration/MemberConfigurationExpression.cs, src/AutoMapper/Configuration/MemberPath.cs, src/AutoMapper/Configuration/PathConfigurationExpression.cs, src/AutoMapper/PropertyMap.cs, src/UnitTests/ReverseMapping.cs
=> Avoid conflicts between path maps and property maps

src/AutoMapper/Execution/PropertyEmitter.cs, src/AutoMapper/Execution/ProxyGenerator.cs, src/IntegrationTests.Net4/MapObjectPropertyFromSubQuery.cs, src/UnitTests/InterfaceMapping.cs
=> Generate setters only when they are required

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/NullBehavior.cs
Fixes #2169.
I'm guessing this is not over yet...
=> Use List for most IEnumerable-s

src/AutoMapper/XpressionMapper/XpressionMapperVisitor.cs, src/UnitTests/XpressionMapperTests.cs
Replacement PR for #2167.
Fixes #2166.
=> Fix for #2166 and #2167.

src/AutoMapper/AutoMapper.csproj, src/AutoMapper/Mappers/EnumToStringMapper.cs, src/AutoMapper/Mappers/MapperRegistry.cs, src/AutoMapper/Mappers/StringToEnumMapper.cs, src/AutoMapper/ReflectionExtensions.cs, src/UnitTests/Enumerations.cs, src/UnitTests/UnitTests.csproj
Recreated pull request for #2075
=> Support for EnumMemberAttribute

src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs, src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
=> Ignore properties with no setter

src/AutoMapper/TypeMap.cs, src/UnitTests/ForPath.cs
=> Inherit ForPath

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/Constructors.cs
=> Throw when we cannot create the destination

src/AutoMapper/Configuration/MappingExpression.cs, src/UnitTests/MappingInheritance/IncludeBaseShouldValidateTypes.cs, src/UnitTests/MappingInheritance/ShouldSupportOnlyDestinationTypeBeingDerived.cs
=> Validate included types

src/AutoMapper/TypeMapFactory.cs, src/UnitTests/Constructors.cs
=> Allow constructor mapping for value types

src/AutoMapper/QueryableExtensions/Impl/NullableSourceExpressionBinder.cs, src/IntegrationTests/IntegrationTests.csproj, src/IntegrationTests/Properties/AssemblyInfo.cs, src/UnitTests/Projection/ToStringTests.cs
=> Allow nullable to string conversion

src/IntegrationTests/App.config, src/UnitTests/App.config, src/UnitTests/AssemblyScanning.cs, src/UnitTests/Bug/MultiThreadingIssues.cs, src/UnitTests/TypeConverters.cs
On my laptop, in VS, the tests run four times faster. There is some  improvement on the CI server too.
=> Speed up the tests

src/AutoMapper/Internal/ReflectionHelper.cs, src/AutoMapper/ResolutionContext.cs
From #2246. The ResolutionContext part is unrelated :)
=> Make debugging easier

src/AutoMapper/AdvancedConfiguration.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/IConfigurationProvider.cs, src/AutoMapper/MapperConfiguration.cs, src/Benchmark/FlatteningMapper.cs, src/UnitTests/Bug/MapAtRuntime/MapAtRuntime.cs, src/UnitTests/Bug/MapAtRuntimeWithCollections/MapAtRuntimeWithCollections.cs, src/UnitTests/MaxExecutionPlanDepth.cs
This doesn't really address [the issues](https://github.com/AutoMapper/AutoMapper/pull/1876#issuecomment-270897598), it's coupled with PreserveReferences and so on :) But it's also simple and I'm guessing would cover most cases. So I say let's give it a chance and see how it goes.
=> By default, inline only one level deep

src/AutoMapper/AutoMapper.csproj, src/AutoMapper/Execution/PropertyEmitter.cs, src/AutoMapper/Execution/ProxyGenerator.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/Mappers/NameValueCollectionMapper.cs, src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs, src/AutoMapper/TypeExtensions.cs, src/AutoMapper/XpressionMapper/Extensions/MapperExtensions.cs, src/UnitTests/DynamicMapping.cs, src/UnitTests/InterfaceMapping.cs, src/UnitTests/Internal/CreateProxyThreading.cs, src/UnitTests/Internal/GenerateSimilarType.cs, src/UnitTests/UnitTests.csproj
=> Create proxies on .Net Core

src/AutoMapper/Mappers/ExpressionMapper.cs, src/UnitTests/Bug/ExpressionMappingWithUseAsDataSource.cs
=> Issue 2246 - UseAsDataSource throwing ArgumentNullException.

src/AutoMapper/Execution/ExpressionBuilder.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/ExpressionExtensions.cs, src/AutoMapper/Internal/ExpressionFactory.cs, src/AutoMapper/Mappers/CollectionMapper.cs, src/AutoMapper/Mappers/DictionaryMapper.cs, src/AutoMapper/Mappers/EnumerableMapper.cs, src/AutoMapper/Mappers/EnumerableToDictionaryMapper.cs, src/AutoMapper/Mappers/HashSetMapper.cs, src/AutoMapper/Mappers/Internal/CollectionMapperExpressionFactory.cs, src/AutoMapper/Mappers/ReadOnlyCollectionMapper.cs, src/AutoMapper/Mappers/ToStringDictionaryMapper.cs, src/UnitTests/ExtensionMethods.cs, src/UnitTests/NullBehavior.cs
Fixes #2276.
Sorry for the whitespace thing, the test is at the top.
=> Null check static methods too

src/AutoMapper/Mapper.cs, src/Benchmark/FlatteningMapper.cs, src/UnitTests/ConfigurationValidation.cs, src/UnitTests/Projection/ProjectionTests.cs, src/UnitTests/StaticMapping.cs
=> Enforce calling Mapper.Initialize once

src/AutoMapper/PropertyMap.cs
I guess it could be IEnumerable, but it's no biggie.
=> Remove ifdefs

src/AutoMapper/AssemblyInfo.cs
Added NeutralResourcesLanguageAttribute to AssemblyInfo.cs. Fixes #2303.
=> Added NeutralResourcesLanguageAttribute

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/ValueTypes.cs
Obviously the test is contrived :) (inspired by #2347) The alternative is to wait for it to happen in real code.
=> Preserve references doesn't make sense for value types

src/AutoMapper/MapperConfiguration.cs
Clearly you lose something by calling a delegate. It's not much from what I can see. But you avoid compiling things twice. I initially thought the typed version would be used more often. But I don't know. It seems most people call ```Map<Destination>(object)```, so the Lazy doesn't help and we end up compiling twice anyway.
=> Reuse the compiled expression

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/MappingInheritance/PreserveReferencesWithInheritance.cs
=> Consider derived maps when setting PreserveReferences

src/AutoMapper/ConfigurationValidator.cs, src/UnitTests/CollectionMapping.cs, src/UnitTests/ReverseMapping.cs
=> Better error message

src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs, src/IntegrationTests/BuiltInTypes/ProjectEnumerableOfIntToList.cs
=> Allow ToList/ToArray for primitive types

src/AutoMapper/AdvancedConfiguration.cs, src/AutoMapper/IConfigurationProvider.cs
Two source files were referencing the "old" github wiki in the comments.
=> Update references to wiki in comments

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/Constructors.cs
=> Consider value types

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Configuration/MemberConfigurationExpression.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/Internal/ExpressionFactory.cs, src/AutoMapper/PropertyMap.cs, src/UnitTests/Bug/RecognizeDestinationPostfixes.cs
=> The MapFrom should have higher priority than postfixes

src/AutoMapper/ProfileMap.cs, src/UnitTests/Bug/TypeMapIncludeBaseTypes.cs
=> Include<,> and IncludeBase<,> is not creating equal TypeMap.IncludedBaseTypes

src/UnitTests/CollectionMapping.cs
=> Test for #2486

src/AutoMapper/MapperConfiguration.cs
As featured in _git commit -m "fix whitespace"_ at [PubConf](https://pubconf.io/) after NDC London 2018.
=> fix whitespace

src/AutoMapper/QueryableExtensions/Impl/MappedTypeExpressionBinder.cs, src/IntegrationTests/Inheritance/ProjectToAbstractType.cs
=> Return the same type on both branches

docs/Custom-value-resolvers.md
=> Missing closing bracket in example code

src/AutoMapper/Configuration/MapperConfigurationExpression.cs, src/UnitTests/ConfigurationRules.cs
=> ##2594: Remove empty profile name from MapperConfigurationException

src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs, src/AutoMapper/QueryableExtensions/Impl/SourceInjectedQueryProvider.cs, src/AutoMapper/QueryableExtensions/NullsafeQueryRewriter.cs
- Include MIT license (with permission statement)
- Include Copyright statement by Axel Heer
- Include link to original source
#2235
=> Extract NullsafeQueryRewriter to separate licensed file

src/AutoMapper/AutoMapperConfigurationException.cs, src/UnitTests/DynamicMapping.cs
Unrelated. Maybe in 7.0 we could support [SourceLink](https://github.com/dotnet/sourcelink).
=> Say that it's a dynamic map when validation fails

src/AutoMapper/QueryableExtensions/Impl/MemberGetterExpressionResultConverter.cs, src/AutoMapper/TypeDetails.cs, src/IntegrationTests/ICollectionAggregateProjections.cs, src/IntegrationTests/IEnumerableAggregateProjections.cs, src/UnitTests/Bug/CannotMapICollectionToAggregateSumDestination.cs, src/UnitTests/Bug/CannotProjectIEnumerableToAggregateDestinations.cs
Fixes the main issue in #2593.
=> Fix projection to destinations using extension methods #2593

src/AutoMapper/Internal/ReflectionHelper.cs, src/UnitTests/Mappers/DynamicMapperTests.cs, src/UnitTests/Mappers/StringDictionaryMapperTests.cs
We should be more forgiving, I guess :) From #2633.
=> Dynamic mapping : Map null to the default for value types

docs/Before-and-after-map-actions.md
Fix constructor name in the document.
=> Fix SetTraceIdentifierAction constructor name

src/AutoMapper/QueryableExtensions/Impl/NullableDestinationExpressionBinder.cs, src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
=> ProjectTo : An edge case with the let clause

src/AutoMapper/AutoMapper.csproj
=> Adding sourcelink to enable PDB debugging

src/AutoMapper/AutoMapper.csproj
Actually I'm not sure what should be done here, if anything.
=> System.ValueTuple is included from 4.7 on

src/AutoMapper/IConfigurationProvider.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/ProfileMap.cs, src/UnitTests/MappingInheritance/OpenGenericsWithInheritance.cs
=> Check for generic instances of included maps

src/AutoMapper/MapperConfiguration.cs, src/UnitTests/ConfigurationValidation.cs
=> AssertConfigurationIsValid(profileName) should throw if name does not exist

src/AutoMapper/TypeExtensions.cs
Sorry, I just had to fix this before I could go on with my talk here at NDC Sydney.
=> fixed whitespace

AutoMapper.sln, docs/8.0-Upgrade-Guide.md, src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/IMappingExpression.cs, src/AutoMapper/TypeMap.cs, src/IntegrationTests/MaxDepth/NestedDtos.cs, src/UnitTests/IMappingExpression/NonGenericConstructorTests.cs, src/UnitTests/Projection/ConstructorTests.cs
=> Consolidate construct using

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/BidirectionalRelationshipsWithoutPR.cs
=> Consider ForPath when checking for cycles

docs/8.0-Upgrade-Guide.md, src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Configuration/SourceMappingExpression.cs, src/AutoMapper/ISourceMemberConfigurationExpression.cs, src/UnitTests/ConditionalMapping.cs, src/UnitTests/MappingInheritance/SourceValidationWithInheritance.cs, src/UnitTests/ReverseMapping.cs
This needs smth in the upgrade guide when we're done.
=> Rename ISourceMemberConfigurationExpression.Ignore to DoNotValidate

default.ps1
=> Remove the symbols package

docs/Dependency-injection.md
Added example from Castle Windsor. 
Removed "Gotchas" and added a section describing how to use QueryableExtensions with DI.
=> Added example for Castle Windsor

src/AutoMapper/Configuration/Internal/PrimitiveHelper.cs, src/AutoMapper/Configuration/PrimitiveExtensions.cs, src/AutoMapper/Execution/DelegateFactory.cs, src/AutoMapper/Mappers/Internal/ElementTypeHelper.cs, src/AutoMapper/Mappers/MapperRegistry.cs, src/AutoMapper/Mappers/ReadOnlyCollectionMapper.cs, src/AutoMapper/Mappers/ReadOnlyDictionaryMapper.cs, src/UnitTests/Mappers/ReadOnlyCollectionMapperTests.cs, src/UnitTests/Mappers/ReadOnlyDictionaryMapperTests.cs
=> Read only dictionaries support

src/AutoMapper/ReflectionExtensions.cs, src/AutoMapper/TypeMapFactory.cs, src/UnitTests/Bug/NullConstructorParameterName.cs
Fixes #2882. Closes #2884. Maybe I should drop that test and make some things public so I can write a white box test.
=> A constructor parameter with no name won't match anything

src/AutoMapper/PropertyMap.cs, src/UnitTests/OpenGenerics.cs
=> Generics with untyped MapFrom

src/AutoMapper/Configuration/MapperConfigurationExpression.cs, src/AutoMapper/IMapperConfigurationExpression.cs, src/UnitTests/AddProfiles.cs
- Simple foreach that calls AddProfile for each element of the sequence
- Added unit test AddProfiles.cs
Fixes #2942.
=> Added AddProfiles method that takes an IEnumerable<Profile>

src/AutoMapper/AutoMapAttribute.cs, src/UnitTests/AttributeBasedMaps.cs
Adding the following configuration options by the AutoMap attribute
- ConstructUsingServiceLocator
- MaxDepth
- PreserveReferences
- DisableCtorValidation
- TypeConverter
#2936
=> AutoMap attribute configuration options

docs/Getting-started.md
Added a link to direct users to the DI page for Asp.NET Core Implementations
=> Link to ASP.NET Core configuration setup

docs/Dependency-injection.md
Include a brief ASP.NET Core Example to help newbies like me
=> Include a brief ASP.NET Core Example

src/AutoMapper/Configuration/IPropertyMapConfiguration.cs, src/AutoMapper/Configuration/MapperConfigurationExpression.cs, src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Configuration/MappingExpressionBase.cs, src/AutoMapper/Configuration/MemberConfigurationExpression.cs, src/AutoMapper/Configuration/MemberPath.cs, src/AutoMapper/Configuration/PathConfigurationExpression.cs, src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/DefaultMemberMap.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/ExpressionExtensions.cs, src/AutoMapper/IMappingExpression.cs, src/AutoMapper/IMappingExpressionBase.cs, src/AutoMapper/IMemberMap.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/PathMap.cs, src/AutoMapper/ProfileMap.cs, src/AutoMapper/PropertyMap.cs, src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs, src/AutoMapper/TypeMap.cs, src/AutoMapper/TypePair.cs, src/IntegrationTests/IncludeMembers.cs, src/UnitTests/AssemblyScanning.cs, src/UnitTests/AutoMapper.UnitTests.csproj, src/UnitTests/IMappingExpression/IncludeMembers.cs, src/UnitTests/ReverseMapping.cs, src/UnitTests/TypeConverters.cs, src/UnitTests/ValueTransformers.cs
=> Include members 

src/AutoMapper/AutoMapper.csproj, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/MapperConfiguration.cs, src/AutoMapper/ProfileMap.cs, src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs, src/AutoMapper/TypeMap.cs
=> Dropping value tuples.

src/AutoMapper/Profile.cs
=> Obsolete Profile.CreateMissingTypeMaps

src/AutoMapper/Configuration/MappingExpression.cs, src/AutoMapper/Configuration/MappingExpressionBase.cs, src/UnitTests/ForAllOtherMembers.cs
=> Match members by name

src/AutoMapper/AutoMapAttribute.cs, src/AutoMapper/Configuration/MapperConfigurationExpression.cs, src/UnitTests/AttributeBasedMaps.cs
Fixes #3049.
This is a rough first pass to enable this. All existing tests are green, but it needs some specifically covering the multiple attribute use scenario.
=> Enabled multiple usage of AutoMapAttribute

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/BidirectionalRelationshipsWithoutPR.cs
=> Resolve can create new maps

src/AutoMapper/ResolutionContext.cs, src/UnitTests/UsingEngineInsideMap.cs
=> Null check

src/AutoMapper/Internal/ExpressionFactory.cs, src/AutoMapper/TypeExtensions.cs, src/UnitTests/ExtensionMethods.cs
=> Check for extension methods

.github/lock.yml
=> Lock stale issues

src/AutoMapper/AutoMapperConfigurationException.cs, src/AutoMapper/ConfigurationValidator.cs, src/AutoMapper/MapperConfiguration.cs, src/UnitTests/CollectionMapping.cs, src/UnitTests/ConfigurationValidation.cs, src/UnitTests/Constructors.cs, src/UnitTests/ReverseMapping.cs
=> Validate all member maps, not only the property maps

src/AutoMapper/TypeMap.cs, src/UnitTests/IMappingExpression/IncludeMembers.cs
=> IncludeMembers with Include

src/AutoMapper/ConstructorParameterMap.cs, src/UnitTests/ConfigurationValidation.cs
=> Use the type the expression would return

src/AutoMapper/Configuration/MappingExpressionBase.cs, src/AutoMapper/IMappingAction.cs, src/UnitTests/BeforeAfterMapping.cs
```
Adding ResolutionContext to IMappingAction<TSource, TDestination>.Process()
#3105
```
=> Adding ResolutionContext to IMappingAction<TSource, TDestination>.Process()

src/AutoMapper/ApiCompatBaseline.txt, src/AutoMapper/Mapper.cs, src/UnitTests/NullBehavior.cs
I don't know if it's worth the breaking change, but it makes sense.
=> Respect AllowNullCollections

src/AutoMapper/ResolutionContext.cs, src/UnitTests/ContextItems.cs
https://github.com/AutoMapper/AutoMapper/issues/3143#issuecomment-506262412
=> When using the context, check that the right Map overload was used

src/AutoMapper/ResolutionContext.cs
=> Public Source property for ContextCacheKey

src/AutoMapper/Internal/ExpressionFactory.cs, src/UnitTests/CollectionMapping.cs
=> Call dispose on the enumerator while avoiding boxing

docs/Dependency-injection.md
Fixes https://github.com/AutoMapper/AutoMapper/issues/3146.
=> Added concrete example to the ASP.NET Core dependency injection types

src/UnitTests/AssemblyScanning.cs
That test is flaky. Hopefully this solves it.
=> Help the runtime find the AM assembly

src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs, src/IntegrationTests/IEnumerableMemberProjections.cs
=> Match destination enumerable types with it's enumerable for LINQ

Directory.Build.props, ISSUE_TEMPLATE.md, docs/Dependency-injection.md
We could do it in the first PR to come, but we'll most likely forget :) Apparently GitHub changed a few things about the issue template. Check https://help.github.com/en/articles/creating-issue-templates-for-your-repository.
=> Version bump

src/AutoMapper/ApiCompatBaseline.txt, src/AutoMapper/Configuration/MappingExpressionBase.cs, src/AutoMapper/ConstructorParameterMap.cs, src/AutoMapper/DefaultMemberMap.cs, src/AutoMapper/IMemberMap.cs, src/AutoMapper/PropertyMap.cs, src/AutoMapper/TypeMap.cs, src/UnitTests/BasicFlattening.cs
=> Consider flattened members as mapped for source validation

src/AutoMapper/ApiCompatBaseline.txt, src/AutoMapper/Configuration/MemberConfigurationExpression.cs, src/AutoMapper/DefaultMemberMap.cs, src/AutoMapper/Execution/ExpressionBuilder.cs, src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/IMemberConfigurationExpression.cs, src/AutoMapper/IMemberMap.cs, src/AutoMapper/PropertyMap.cs, src/UnitTests/MappingInheritance/IncludedMappingShouldInheritBaseMappings.cs
I've already increased the minor version in another PR.
=> Inherit UseDestinationValue. Add DontUseDestinationValue.

docs/Expression-Translation-(UseAsDataSource).md
=> Update Expression doc to add configuration line

src/AutoMapper/ApiCompatBaseline.txt, src/AutoMapper/Configuration/PrimitiveExtensions.cs, src/AutoMapper/Execution/DelegateFactory.cs, src/AutoMapper/Execution/ExpressionBuilder.cs, src/AutoMapper/TypeDetails.cs, src/UnitTests/Bug/AllowNullDestinationValuesBugs.cs
I guess this will break some existing code. Fixes #3267.
=> Honour AllowNullDestinationValues

src/AutoMapper/AutoMapperMappingException.cs
=> Removed dead links in Exception class

src/AutoMapper/AutoMapper.csproj, src/IntegrationTests/AutoMapper.IntegrationTests.csproj, src/UnitTests/AutoMapper.UnitTests.csproj
- Upgrade to Stable Microsoft.SourceLink.GitHub
- Bump Minors for xunit and Shouldly
=> NuGet Package Maintenance 

README.md, docs/Enum-Mapping.md, docs/index.rst
Added documentation for enum-mapping
=> Enum mapping documentation

src/AutoMapper/ValueTransformerConfiguration.cs, src/UnitTests/ValueTransformers.cs
=> The source type must be assignable to the type of the transformation

docs/8.1.1-Upgrade-Guide.md, docs/index.rst
I've added a short explanation of the change in default behaviour in 8.1.1.
I'm afraid I couldn't work out how to actually generate the docs.
Fixes #3344.
=> Add brief documentation for 8.1.1 upgrade

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/AutoMapper/TypeMap.cs, src/UnitTests/OpenGenerics.cs
Similar to generic type converters.
=> Generic value resolvers

docs/Understanding-your-mapping.md
Added links to DotNetFiddle and blog showing how to use ReadableExpressions with AutoMapper.
=> Links to more ReadableExpressions resources

src/AutoMapper/Internal/MapMemberVisitor.cs, src/AutoMapper/Internal/ReflectionHelper.cs, src/AutoMapper/MapMemberInfo.cs, src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs, src/AutoMapper/QueryableExtensions/ProjectionExpression.cs, src/UnitTests/Projection/ExplicitExpansionWithIncludeBase.cs
=> Fix for Issue #3422

.github/workflows/lock.yml
I don't think it needs to run daily.
=> Run lock weekly

src/AutoMapper/Execution/TypeMapPlanBuilder.cs, src/UnitTests/OpenGenerics.cs
=> Generic destination value resolver

src/AutoMapper/Internal/TypeExtensions.cs, src/UnitTests/CollectionMapping.cs
=> Return the first method we find

README.md
https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org
Apparently they plan [improvements](https://github.com/NuGet/NuGetGallery/issues/8837).
=> Nuget readme rendering

src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
Fixing up some relationships and Id Initialization for CEntities. Original code was based on in-memory unittest, which had less relationship issues. #3869
=> Fix EF6 relationships and Id initialization

src/AutoMapper/Execution/ExpressionBuilder.cs, src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs, src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
=> Handle identity lambda resolvers with ProjectTo subquery

README.md
Summary of the changes (Less than 80 chars)
- install command from CLI is added in README.md
=> install command from cli is added in README.md

src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs, src/IntegrationTests/IncludeMembers.cs, src/UnitTests/Projection/ConstructorTests.cs
I added the tests
Im mighty impressed with how little changes to the code you have been able to pull this off
=> added tests

src/AutoMapper/ApiCompat/PreBuild.ps1, src/AutoMapper/AutoMapper.csproj
@jbogard Let's merge this, cause the CI is broken.
=> We build for .net 6 now

src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs, src/IntegrationTests/Inheritance/PolymorphismTests.cs
=> Fix polymorphic mapping when some derived types have explicit mappings and others do not
